suggest(Actual_plan_context, Goals, Contributions, Identity_traits, Final_Suggestions, Mixed_suggestions) :- 	 find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions), find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions), find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions), append(Goals_suggestions, Contributions_suggestions, Pre_partial_suggestions), append(Pre_partial_suggestions, Identity_suggestions, Partial_suggestions), extra_Suggestion(Actual_plan_context, ExtraSuggestion),append(Partial_suggestions, ExtraSuggestion, Final_Suggestions), find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions). 
 
extra_Suggestion(Actual_plan_context, ExtraSuggestion):- 
findall( Suggestion, find_extra_suggest(Actual_plan_context,Suggestion),  ExtraSuggestion).  


find_extra_suggest(Actual_plan_context,Suggestion) :- can_suggest(Actual_plan_context, Suggestion),final_suggest(Suggestion).


/*suggest(Actual_plan_context, Goals, Contributions, Identity_traits, Final_suggestions) :- 	 find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions), find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions), find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions), find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions), append(Goals_suggestions, Contributions_suggestions, Pre_partial_suggestions), append(Pre_partial_suggestions, Identity_suggestions, Partial_suggestions), append(Partial_suggestions, Mixed_suggestions, Final_suggestions).*/


find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions) :- findall( Suggestion, find_one_objetives_suggestion(Actual_plan_context, Goals, Suggestion),  Goals_suggestions).

find_one_objetives_suggestion(Actual_plan_context, Goals, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Goal,Goals),  valid_objetives_rule(Goal,Suggestion).

find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions) :- findall( Suggestion, find_one_contributions_suggestion(Actual_plan_context, Contributions, Suggestion),  Contributions_suggestions).

find_one_contributions_suggestion(Actual_plan_context, Contributions, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Contribution,Contributions),  valid_contribution_rule(Contribution,Suggestion).

find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions) :- findall( Suggestion, find_one_identity_suggestion(Actual_plan_context, Identity_traits, Suggestion),  Identity_suggestions).

find_one_identity_suggestion(Actual_plan_context, Identity_traits, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Caracteristica_identidad,Identity_traits),  valid_identity_rule(Caracteristica_identidad,Suggestion).

find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions) :- append(Goals, Contributions, Pre_mixed_traits_list), append(Pre_mixed_traits_list, Identity_traits, Mixed_traits_list),  findall( Suggestion, find_one_mixed_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion),  Pre_Mixed_suggestions), findall( Suggestion, find_one_advanced_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion),  Post_Mixed_suggestions), append(Pre_Mixed_suggestions, Post_Mixed_suggestions, Mixed_suggestions). 

find_one_mixed_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(First_trait, Mixed_traits_list), member(Second_trait, Mixed_traits_list), regla_valida_combinacion(First_trait,Second_trait, Suggestion).

find_one_advanced_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(First_trait, Mixed_traits_list), member(Second_trait, Mixed_traits_list), member(Third_trait, Mixed_traits_list), regla_avanzada_combinacion(First_trait,Second_trait, Third_trait, Suggestion).


% RULES
% TODO Revisar que las sugerencias de todas las reglas esten almenos en uno de los planes (excepto la de error), asi no olvide agregarlas ahi
can_suggest(commercial_plan, direct_marketing).
can_suggest(commercial_plan, logistic_association).
can_suggest(commercial_plan, international_contacts).
can_suggest(commercial_plan, outsource_sales).
can_suggest(commercial_plan, start_selling_followers).
can_suggest(commercial_plan, trade_show).
can_suggest(commercial_plan, embassy_association).
can_suggest(commercial_plan, international_association).
can_suggest(commercial_plan, brand_association).
can_suggest(commercial_plan, politic_mayor_association).
can_suggest(commercial_plan, hire_business_manager).
can_suggest(commercial_plan, work_near_clients).
can_suggest(commercial_plan, use_CRM).
can_suggest(commercial_plan, meetings).
can_suggest(commercial_plan, samples).
can_suggest(commercial_plan, target_massive_markets).
can_suggest(commercial_plan, carefull_deadlines).
can_suggest(commercial_plan, sell_talks).
can_suggest(commercial_plan, sell_workshops).
can_suggest(commercial_plan, logistics).
can_suggest(commercial_plan, logistic_partner).
can_suggest(commercial_plan, travel_strategically).
can_suggest(commercial_plan, mercadopago).
can_suggest(commercial_plan, sell_to_banks).

can_suggest(management_plan, find_funding).
can_suggest(management_plan, save_for_urgency).
can_suggest(management_plan, hire_secretary).
can_suggest(management_plan, use_personal_agenda).
can_suggest(management_plan, disconnect).
can_suggest(management_plan, find_partner_for_support).
can_suggest(management_plan, plan_breaks).
can_suggest(management_plan, invest_on_your_business).
can_suggest(management_plan, aduana_suppliers).
can_suggest(management_plan, known_partner_divide_roles).
can_suggest(management_plan, outsource_control).
can_suggest(management_plan, systematize).
can_suggest(management_plan, assign_roles).
can_suggest(management_plan, weekly_meetings).
can_suggest(management_plan, define_billing_process).
can_suggest(management_plan, therapy).
can_suggest(management_plan, do_sport).
can_suggest(management_plan, keep_yourself_busy).
can_suggest(management_plan, talk_partner_objetives).
can_suggest(management_plan, carefull_deferred_payment).
can_suggest(management_plan, cross_control).
can_suggest(management_plan, design_processes).
can_suggest(management_plan, monitor_employees).
can_suggest(management_plan, explain_how_to_delegate).
can_suggest(management_plan, consultant_or_coach).
can_suggest(management_plan, hire_experienced_employees).
can_suggest(management_plan, organize_billing).
can_suggest(management_plan, arrange_bank_loans).
can_suggest(management_plan, arrange_passport).
can_suggest(management_plan, take_time_communicate).
can_suggest(management_plan, talk_directly_about_problems).
can_suggest(management_plan, relaxing_decorations).
can_suggest(management_plan, digital_payments).
can_suggest(management_plan, local_payments).
can_suggest(management_plan, update_netbook).
can_suggest(management_plan, everything_online).
can_suggest(management_plan, outsource_accounting).
can_suggest(management_plan, strengthen_leading_experience).
can_suggest(management_plan, learn_leadership).
can_suggest(management_plan, self_managed_team).
can_suggest(management_plan, consultant_100_percent_online_and_notebook_updated).
can_suggest(management_plan, be_ordered_and_disciplined).

can_suggest(communication_plan, paid_ads).
can_suggest(communication_plan, local_social_networks).
can_suggest(communication_plan, digital_store).
can_suggest(communication_plan, physical_communications).
can_suggest(communication_plan, digital_communications).
can_suggest(communication_plan, talks_workshops).
can_suggest(communication_plan, ecommerce_association).
can_suggest(communication_plan, investors_deck_ready).
can_suggest(communication_plan, communication_association).
can_suggest(communication_plan, outsource_communications).
can_suggest(communication_plan, communicate_methodology).
can_suggest(communication_plan, care_about_design).
can_suggest(communication_plan, influencers).
can_suggest(communication_plan, use_achievements_branding).
can_suggest(communication_plan, guerrilla_marketing).
can_suggest(communication_plan, press_and_magazines).
can_suggest(communication_plan, client_frequent_places).
can_suggest(communication_plan, drawing_as_clear_as_posible).


can_suggest(legal_plan, create_sas).
can_suggest(legal_plan, iva_90_days_delay).
can_suggest(legal_plan, travel_documents).
can_suggest(legal_plan, accounting_balance).
can_suggest(legal_plan, handle_payments).
can_suggest(legal_plan, tax_checklist).
can_suggest(legal_plan, public_accountant).
can_suggest(legal_plan, money_really_took).
can_suggest(legal_plan, salaries_check).
can_suggest(legal_plan, cross_check_control).
can_suggest(legal_plan, ensurance).
can_suggest(legal_plan, register_brand).
can_suggest(legal_plan, money_requirements).
can_suggest(legal_plan, dont_reveal_strategies_on_the_web).
can_suggest(legal_plan, make_a_work_contract).

can_suggest(marketing_plan, sustitute_products).
can_suggest(marketing_plan, pro_network).
can_suggest(marketing_plan, study_competitors).
can_suggest(marketing_plan, understand_customer).
can_suggest(marketing_plan, understand_product).
can_suggest(marketing_plan, aim_premium). 
can_suggest(marketing_plan, prearmed_dresses_published).
can_suggest(marketing_plan, understand_customer_and_product).


valid_objetives_rule(wants_recognition, direct_marketing).
valid_objetives_rule(wants_recognition, talks_workshops).
valid_objetives_rule(wants_recognition, meetings).
valid_objetives_rule(wants_recognition, trade_show).
valid_objetives_rule(wants_recognition, press_and_magazines).
valid_objetives_rule(wants_recognition, influencers).
valid_objetives_rule(wants_recognition, client_frequent_places).
valid_objetives_rule(wants_recognition, talks_workshops).
valid_objetives_rule(wants_brag, direct_marketing).
valid_objetives_rule(wants_brag, talks_workshops).
valid_objetives_rule(wants_brag, meetings).
valid_objetives_rule(wants_brag, trade_show).
valid_objetives_rule(wants_brag, press_and_magazines).
valid_objetives_rule(wants_brag, influencers).
valid_objetives_rule(wants_brag, client_frequent_places).
valid_objetives_rule(wants_brag, talks_workshops).
valid_objetives_rule(wants_money, find_funding).
valid_objetives_rule(wants_money, investors_deck_ready).
valid_objetives_rule(wants_money, target_massive_markets).
valid_objetives_rule(wants_money, money_requirements).
valid_objetives_rule(travel, trade_show).
valid_objetives_rule(travel, international_contacts).
valid_objetives_rule(travel, update_netbook).
valid_objetives_rule(travel, everything_online).
valid_objetives_rule(travel, digital_payments).
valid_objetives_rule(travel, travel_documents).
valid_objetives_rule(have_fun, trade_show).
valid_objetives_rule(physical, aduana_suppliers).
valid_objetives_rule(physical, samples).
valid_objetives_rule(physical, logistic_association).
valid_objetives_rule(physical, logistics).
valid_objetives_rule(physical, carefull_deferred_payment).
valid_objetives_rule(global, international_contacts).
valid_objetives_rule(global, digital_payments).
valid_objetives_rule(global, everything_online).
valid_objetives_rule(local, local_social_networks).
valid_objetives_rule(local, digital_store).
valid_objetives_rule(local, local_payments).
valid_objetives_rule(digital, local_social_networks).
valid_objetives_rule(digital, global_social_networks).
valid_objetives_rule(digital, target_massive_markets).
valid_objetives_rule(digital, digital_payments).
valid_objetives_rule(product_and_service, local_social_networks).
valid_objetives_rule(product_and_service, local_social_networks).
valid_objetives_rule(product_and_service, press).
valid_objetives_rule(doesnt_know, local_social_networks).
valid_objetives_rule(doesnt_know, local_social_networks).
valid_objetives_rule(doesnt_know, press).
valid_objetives_rule(allow_association, brand_association).
valid_objetives_rule(allow_association, politic_mayor_association).
valid_objetives_rule(allow_association, influencers).
valid_objetives_rule(allow_association, communication_association).
valid_objetives_rule(allow_association, everything_online).
valid_objetives_rule(allow_sell_talks, talks_workshops).
valid_objetives_rule(allow_sell_talks, sell_talks).
valid_objetives_rule(allow_sell_talks, update_netbook).
valid_objetives_rule(allow_sell_workshops, talks_workshops).
valid_objetives_rule(allow_sell_workshops, sell_workshops).
valid_objetives_rule(allow_sell_workshops, update_netbook).
valid_objetives_rule(strengthen_your_team, consultant_or_coach).
valid_objetives_rule(flexibility, update_netbook).
valid_objetives_rule(flexibility, everything_online).


/*para probar plan legal
valid_objetives_rule(wants_recognition, iva_90_days_delay).
valid_objetives_rule(wants_recognition, tax_checklist).
valid_objetives_rule(travel, travel_documents).
valid_objetives_rule(wants_money, handle_payments).
valid_objetives_rule(flexibility, mercadopago).*/


valid_contribution_rule(has_savings_or_funding, invest_on_your_business).
valid_contribution_rule(has_savings_or_funding, paid_ads).
valid_contribution_rule(has_savings_or_funding, save_for_urgency).
valid_contribution_rule(has_followers, start_selling_followers).
valid_contribution_rule(has_achievements, use_achievements_branding).
valid_contribution_rule(doesnt_have_account, define_billing_process).
valid_contribution_rule(doesnt_have_account, organize_billing).
valid_contribution_rule(doesnt_have_account, arrange_bank_loans).
valid_contribution_rule(doesnt_have_credit_history, arrange_bank_loans).
valid_contribution_rule(doesnt_have_passport, arrange_passport).
valid_contribution_rule(alone, outsource_communications).
valid_contribution_rule(alone, outsource_sales).
valid_contribution_rule(alone, outsource_control).
valid_contribution_rule(alone, hire_business_manager).
valid_contribution_rule(alone, find_partner_for_support).
valid_contribution_rule(alone, update_netbook).
valid_contribution_rule(has_partner, known_partner_divide_roles).
valid_contribution_rule(has_partner, talk_partner_objetives).
valid_contribution_rule(has_experience_leading, strengthen_leading_experience).
valid_contribution_rule(doesnt_have_experience_leading, learn_leadership).
valid_contribution_rule(doesnt_have_experience_leading, monitor_employees).
valid_contribution_rule(doesnt_have_experience_leading, self_managed_team).
valid_contribution_rule(doesnt_have_experience_leading, hire_experienced_employees).


/*valid_contribution_rule(has_savings_or_funding, iva_90_days_delay).
valid_contribution_rule(has_achievements, mercadopago).*/

valid_identity_rule(disorganized, hire_secretary). 
valid_identity_rule(disorganized, personal_agenda). 
valid_identity_rule(disorganized, disconnect). 
valid_identity_rule(disorganized, find_partner_for_support). 
valid_identity_rule(disorganized, plan_breaks). 
valid_identity_rule(disorganized, carefull_deadlines).
valid_identity_rule(extrovert, direct_marketing).
valid_identity_rule(extrovert, contacts).
valid_identity_rule(extrovert, talks_workshops).
valid_identity_rule(extrovert, trade_show).
valid_identity_rule(social, direct_marketing).
valid_identity_rule(social, contacts).
valid_identity_rule(social, talks_workshops).
valid_identity_rule(social, trade_show).
valid_identity_rule(passion, direct_marketing).
valid_identity_rule(passion, talks_workshops).
valid_identity_rule(passion, trade_show).
valid_identity_rule(humorous, direct_marketing).
valid_identity_rule(humorous, talks_workshops).
valid_identity_rule(non_social, digital_communications).
valid_identity_rule(non_social, communication_association).
valid_identity_rule(non_social, outsource_communications).
valid_identity_rule(non_social, outsource_sales).
valid_identity_rule(non_social, take_time_communicate).
valid_identity_rule(non_social, talk_directly_about_problems).
valid_identity_rule(non_social, relaxing_decorations).
valid_identity_rule(creative, digital_communications).
valid_identity_rule(creative, local_social_networks).
valid_identity_rule(creative, global_social_networks).
valid_identity_rule(class_and_style, paid_ads).
valid_identity_rule(class_and_style, digital_store).
valid_identity_rule(class_and_style, communicate_methodology).
valid_identity_rule(class_and_style, care_about_design).
valid_identity_rule(class_and_style, meetings).
valid_identity_rule(class_and_style, aim_premium).
valid_identity_rule(shy_and_afraid, care_about_design).
valid_identity_rule(shy_and_afraid, therapy).
valid_identity_rule(shy_and_afraid, keep_yourself_busy).
valid_identity_rule(shy_and_afraid, outsource_communications).
valid_identity_rule(shy_and_afraid, outsource_sales).
valid_identity_rule(shy_and_afraid, find_partner_for_support).
valid_identity_rule(shy_and_afraid, relaxing_decorations).
valid_identity_rule(shy_and_afraid, talk_directly_about_problems).
valid_identity_rule(shy_and_afraid, register_brand).
valid_identity_rule(stressfully, therapy).
valid_identity_rule(stressfully, do_sport).
valid_identity_rule(stressfully, outsource_communications).
valid_identity_rule(stressfully, outsource_sales).
valid_identity_rule(stressfully, find_partner_for_support).
valid_identity_rule(stressfully, relaxing_decorations).
valid_identity_rule(stressfully, talk_directly_about_problems).
valid_identity_rule(stressfully, update_netbook).
valid_identity_rule(anxious, do_sport).
valid_identity_rule(anxious, therapy).
valid_identity_rule(anxious, keep_yourself_busy).
valid_identity_rule(anxious, relaxing_decorations).
valid_identity_rule(anxious, talk_directly_about_problems).
valid_identity_rule(anxious, update_netbook).
valid_identity_rule(organized, paid_ads).
valid_identity_rule(organized, digital_store).
valid_identity_rule(organized, communicate_methodology).
valid_identity_rule(organized, aim_premium).
valid_identity_rule(transgressor, digital_communications).
valid_identity_rule(transgressor, guerrilla_marketing).
valid_identity_rule(transgressor, carefull_deadlines).
valid_identity_rule(hate_numbers, hire_secretary).
valid_identity_rule(hate_numbers, outsource_accounting).
valid_identity_rule(non_profit, direct_marketing).
valid_identity_rule(non_profit, talks_workshops).
valid_identity_rule(non_profit, local_social_networks).
valid_identity_rule(non_profit, everything_online).
valid_identity_rule(young_client, local_social_networks).
valid_identity_rule(young_client, global_social_networks).
valid_identity_rule(adult_client, paid_ads).
valid_identity_rule(adult_client, digital_store).
valid_identity_rule(adult_client, communicate_methodology).
valid_identity_rule(old_client, paid_ads).
valid_identity_rule(old_client, digital_store).
valid_identity_rule(old_client, communicate_methodology).
% TODO en vez de ponerlas aca, hacer que se adhieran a las Listas para Cada Plan con un Predicado Hecho /1 al final, asi solo aparecen una unica vez en vez de por cada elemento. Ojo con bypassear control de validar puede sugerirse por cada plan
/*
valid_identity_rule(_, explain_how_to_delegate).
valid_identity_rule(_, monitor_employees).
valid_identity_rule(_, design_processes).
valid_identity_rule(_, cross_control).
valid_identity_rule(_, define_billing_process).
valid_identity_rule(_, weekly_meetings).
valid_identity_rule(_, assign_roles).
valid_identity_rule(_, systematize).
valid_identity_rule(_, work_near_clients).
valid_identity_rule(_, use_CRM).
valid_identity_rule(_, communication_association).
*/

/*valid_identity_rule(organized, iva_90_days_delay).
valid_identity_rule(social, mercadopago).*/


regla_valida_combinacion(local, physical, physical_communications).
regla_valida_combinacion(local, physical, press_and_magazines).
regla_valida_combinacion(local, physical, influencers).
regla_valida_combinacion(local, physical, client_frequent_places).
regla_valida_combinacion(global, digital, digital_store).
regla_valida_combinacion(global, digital, talks_workshops).
regla_valida_combinacion(global, digital, digital_communications).
regla_valida_combinacion(global, digital, digital_marketing).
regla_valida_combinacion(global, digital, digital_payments).
regla_valida_combinacion(global, physical, logistic_association).
regla_valida_combinacion(global, physical, ecommerce_association).
regla_valida_combinacion(global, extrovert, international_contacts).
regla_valida_combinacion(global, allow_association, embassy_association).
regla_valida_combinacion(global, allow_association, international_association).
regla_valida_combinacion(extrovert, allow_association, brand_association).
regla_valida_combinacion(social, allow_association, brand_association).
regla_valida_combinacion(extrovert, allow_association, politic_mayor_association).
regla_valida_combinacion(social, allow_association, politic_mayor_association).
regla_valida_combinacion(non_social, allow_association, hire_business_manager).
regla_valida_combinacion(has_savings_or_funding, allow_association, hire_business_manager).
regla_valida_combinacion(has_savings_or_funding, strengthen_your_team, hire_experienced_employees).
regla_valida_combinacion(travel, doesnt_have_passport, arrange_passport).


% CASO 1: diseñadora nomada digital 
%sugerencia comercial 
regla_avanzada_combinacion(global, digital, flexibility, travel_strategically).
%sugerencia administracion 
regla_avanzada_combinacion(global, digital, flexibility, be_ordered_and_disciplined).
%sugerencia comunicacional 
regla_avanzada_combinacion(global, digital, flexibility, communication_association).
%sugerencia legal 
regla_avanzada_combinacion(global, digital, flexibility, make_a_work_contract).
%sugerencia marketing  
regla_avanzada_combinacion(global, digital, flexibility, understand_customer_and_product).


% CASO 2: consultora de diseño y de marcas 
%sugerencia comercial 
regla_avanzada_combinacion(local, physical, creative, direct_marketing).
%sugerencia administracion 
regla_avanzada_combinacion(local, physical, creative, consultant_100_percent_online_and_notebook_updated).
%sugerencia comunicacional 
regla_avanzada_combinacion(local, physical, creative, digital_communications).
%sugerencia legal 
regla_avanzada_combinacion(local, physical, creative, dont_reveal_strategies_on_the_web).
%sugerencia marketing  
regla_avanzada_combinacion(local, physical, creative, study_competitors).




% CASO 3: pibe que es modista 
%sugerencia comercial 
regla_avanzada_combinacion(global, physical, alone, logistic_partner).
%sugerencia administracion 
regla_avanzada_combinacion(global, physical, alone, find_partner_for_support).
%sugerencia comunicacional 
regla_avanzada_combinacion(global, physical, alone, drawing_as_clear_as_posible).
%sugerencia legal 
regla_avanzada_combinacion(global, physical, alone, handle_payments).
%sugerencia marketing  
regla_avanzada_combinacion(indumentaria, physical, alone, prearmed_dresses_published).

% AGREGAR AGUERRIDO A CUARTO CASO (EL DE LEO)
regla_avanzada_combinacion(galeria, transgressor, physical, sell_to_banks).

% TODO Guido Yari agreguen mas sugerencias aca y los textos en el es.i18n.json


final_suggest(create_sas).
final_suggest(iva_90_days_delay).
final_suggest(accounting_balance).
final_suggest(handle_payments).
final_suggest(tax_checklist).
final_suggest(mercadopago).
final_suggest(public_accountant).
final_suggest(money_really_took).
final_suggest(salaries_check).
final_suggest(cross_check_control).
final_suggest(ensurance).

final_suggest(sustitute_products).
final_suggest(pro_network).
final_suggest(study_competitors).
final_suggest(understand_customer).
final_suggest(understand_product).

/* PARA PROBAR ONLINE
https://tio.run/##7X1Zj6vatt5z9q8oKYp079XOwYAxJk@4wWD6HkwUlWgNmL6HP3@Da3VVq1xl1z77RImUh6VaZY9vzMEc/WyoosqT/Pzf6z76z/@s2/PZr5t/27hNayfPRWJnz26eNf7Q/PlE5nZS//m0m3@vIqdtojybfz16ftZEzfjcVHbUzB8comyGKt84faPhosH3nutfH/370//470//5SmIMu85d2K/iTq/fk3wqQQvP96w@/MbK/e1aPfZ/fYku4/QP9hHPx71Lud3k3K8AZ3Z2kXhZ96/vXugT4T580ms/OfCrppoHvYmuw8Ibksx87vJa36Oyn6lxtsPSlypfhH9@58/RLg1/G/EN0zlx0ynvxvMP2WR783vH09/PP3x155wNtw/rjLaSfJvT68f5kXwbzw/c6PXk/X0jvs/np7@@OOPr7O6@pM7f/WpA78eOniZ@h/kryWYxwf@4@8LBP/f6995/f8RE/@/Orh8FiXePcotS/rHfwA//OTvsKSrYX7s1Hnm3xzl00He@vn7If/xQ/x/kvlV9K@5/lPqp45fvRjGny8MrxJ2dhK9nsyqTfxvJG@Dw7/U5e7r4aORHxr4rU4@FuO1bv6uAf@6nl7z/PPNAL/09lrKb6p7g7qhwr87rN1X3Y0RHxzwrd5uDv9aZX/LQP@EvuzKdhu/iubPXfu7NJ7t/fnbcL@091Pgb5r7CH9Di//qLHKdhdd55B2Pazr4JsQ3Js/JLPbbbPHu6w9Hfsvijjn9/ui3n5x7P/hba7pKeCt7fj647XV25v4t4@d18/xJ@r4p358fwD6odf/4Wyftr3vGIapmqV/43lb5dzrFn9l4nxFW/jmxn1@8x57HTJ25QnCvz/N6iLdsbnjP36jJ/xsm5TuhGkbVA5Nnz8892Q9P3xuuv/UL/@1J1lhCmX@qwl54kv0uqu3qqWz9p8Sun@Yp8Ss/c6P5/57/1OTe/J/rFy@C1E8zJz97spPUz/L5t@ypzfIrYTL/dp0/v376N39w/aLJZ9j1G7@q8urqI3X0NNPmSTdHySf7PDO0qytLO4z@eK2N@RlTv3Kj7xr588mLKt9tnlO7uswFT3aen@NT@iQ/v8TjZ7uu8/nz78/@KSaatV5lL6TzZ1cjmON6fQ@Vt02dt5XrP9d24t8lr5u5iH6u/SSZn@I5yJMk7/3qLqyxk0v93OfVpQ7z4j55ZXuzQGHe36OcbXCeovGvz9MXgE5lzwb6BUCRJ9FViak95tXXRAySdjbhB2Z29hP/2WnraLbbeh4ps2frvwe6KuI58@3q2U2iOTfeHaWt/eedzN0jS/0X675vRXZaPGBss62d/avX1PXcJHz3nrso1678oE2SZ8@3veQ6L3fFmc35@cVEH6J82Ix/ePHDhC@tbvaivzeAb2qdA1bzHfCST4I2897Hkne0tT3PXTAbYDvPZuaO9@hfLKr23cqf5/8u9dUyitlOvznTPIBn34N4UT1Hp2wOiPcoXx7z@5y8PELdFkVe3cW9pEGn8u13Gn1HGmVz@9nMufl5nMPgT0@6B7O9dv7oRZ7Zg6q79Jcs77Ofj@JF1wzyXOXvneAd8leAfum68uSuvsc5waVznJn8u08xO9Y5e0yO3vcvyfj8gYu/V7I/K2@OTNG3TFFUufvAtDahX9nFXaPz8uf6ETu4@H7xotfZb4Orbu9yvkaBn2r6uTxxD/Uq5ARzseBfjXa8fn8XWOVz1H5QsZ7/oq3vU3lfqjTPomZ2Gn8Otvno3wf4w/wzyp7nvPvc5PPDJHOB09y1oln8uk0ae/5gHs3NbTd8KMbMw81tp/9SDj8sY16d7Ww27R@WddfEqzlrn2dyO7s8J7md1Y8iitk7HjGyxr74z02UXh00Tdts7qLvz9mLnX2rCmensp3Zy6@KdRI/vStg5Sf2cHUqby6ZK/vHisSdmHuOmmu@@WaXd@mT3P0CdVt48zPPFUXj5Pnlrpl1fjU24fUJ8uyaoB8Pgbbr5m3WPJL1mrkHOM/xJHtO5jrgOtgve7v79HNp9A03h/YwKu4Odg0v3z6dmxbfTn9P4L8s47pi9j1J2dFcTXq3ioPfSb9p46V8TK6z/FKBPID7ofV6DgP@A/RFONaR@9I9vPryKyN9GXi/M/gd4X8vn/w7FfXvuG@ZPq/qq99cnufqwBsfgL397GtDvs7dX5yXV7FkzrlNmHvXffOHBJ6T0feI8i1jPDQ3nzUcv1Nfa745yEezI7@Eh@eXzuh2W/s79tzOCXIO3fanzfA7w6yu3c21/Urtsz19UNS/m4mX5uY5qPyy/e6s7gvwj7feeU1zP7uH2S6aazP8@wCviaLOfsYWz549Xo0pscdPaOdetvPnyiB321ux9DXpr@g2p6vEfh@oXhOH82wk/kch@o0E9vDshrPNvyzIfEx3dSrbywv7nH9CVbROcl2Y@CarnX3KMc/88eppyZzkmvep4TVtPT/xHJ3rb6J@Qvi9ZrpSfVA5vab259qkujOVlX9tv@aC78WOH3iesp0z949p/y01fDfqH0/Vzn1d084WNWd3r3Vv5NK3gJnsR4S/Q1k3rTdeA0sxf3qNa3fo525xdu/m6kTuLFWevlsn@ATxXfo7ADtKZ0o/jdr0ZSH4j5vbfL19jRlz6ZOf5wL1ZaX7xvrYo9D3CeRR5KtW5uHBXi9MPQq6HbweRb8NzY@iPgx9/5Jpnf3m/FUlfsP8hWEeU9t39g/q6xv1lxX1Dfawhr6R/xXV/IXJeolV71aK7gM@KJPuAz9crbsPvRlXb8K@ZdNHFPuD8sNl8U9R7zqaT6lvdTSfAm60Y/ce9/ci4iZ9@LLW1z4UqX4U@zcXs@4gfi3g3iH8YCPjQdQDA3y29HITek5yx/6yXfxAPaq4H/QPW8ZLi/dxp/cZ5vcu7z7/e9J/5/hFcX6ivj38l2FfCyA/YY@q5HsJ8xLfa7/qItf/4gP@izi8pJ0PHzP36zlJXNePv6qOvwf5qXT2df/vtW/f3iV7FPvZhtmjPB7IxjdQn3X5j/J42Ne/YX/tOj2c2d8D32xdPYh5LLe9wv2U668I@gr8bvfsC9jHhH616veynXNdi/togfomgyDxh8iJZjMcHx3zDeSWDVxPOBd2ZV97O8euXnannl7aysebgBsLDo9X8m/b/7@l0HhTvr1firg/UW8WG16O1350tDC06@fa7q4l/1V932vZz3buvsrp1UrsV6E3Nlc/Y/HzwMRnJyk@Y/B62e3zhbiPuHwP7i@V4vdFnE92677E5cbezJfwN/dqHuHgznVfNP8/upZA4z/B6Meez81doI8Y2MnsBp8u9j6M/HEG5wtD/VgAuwP56JzIHdgnO/B3kB8Ez9tm/X2EO/vkD3H4cAf3M/SvraEfu0X3d5AesadbfG9sLv1VVrd2eP8qr1t7WH@V16fbu9d0@OVY/2H@eyRMvss1t85Be1H9I3557w/BPD2AeXcM5hHQ68Mwj9B/7JAPifj6YMwjgJuHqW7BrvfH8rn4aT5ZB/wQ8a77/pDyo/rzY8D7dZC3tN96ooel/kF@R@QfZI/J@5P6nrDXbPT5gvkH9I/J8Yv8niBhm@ZV3tYPS/IL8Jgo2ezOv1TzwebyPeD9ru5j7N10/gj0bT7/GPHRGZL7uE@PkdyDf3CS5BbsZV90zqRf1MYv2OcrEB@h7iwl/QZL7O/r93UzJv6Nwv4O/e2VtDugj3fqH4Pf2K5/CPhuH@QO/ZvNudthKBxfAHZQzRP3uGi/436d4nuE@uYhvUeAX/TQj@GfeenvqLsF8efwL3jcu1n9uq@/H/23je6boOa64ndN@uNdVb4mfXUo8y7tV1V3G/up3l5Dvqq019ivaOzNzP0Fdb3Gf9A/vUXY2RB9y8KfT/5Pus/1@ZPsYZ/8ifjCNP0S5utT9BP70PS8rnw/TwVvKvL7SeB1hfyl8P8KeD8ez1VYVp@vNpFXX8y7b6G3D13dxz1c/YcvumivF8LqGzcI7kM@OOL5UQEzW0kQPd5qvIY8Xn7@QHylcnmN@3g/4C1m9rOZ5NuxgK@N9hb5pVrJ9tqk@Qm94x1viR9xkLeIL/pI4j0q2GvSh/z2Ff3HQn2/WOhnT50/XS8AFvmcOF4u@rn2dbnb9b9dN6z9J9sLozmkZk/2yx1Dds6v84@X5f6d7dlP4nWxf24Wn9rsevnXi64rEU@U74b5EwA@2cnTy7tRvl0urGcJnuwZ7Lsv9xLtpxcBX8R4LU01e@bM209eVjjyfzwJcf4yiDNeWzjfrp6@Lwxe6b/dW62eitaff3u5HhnNgf0Xn@uqwB/Af9ycsefPrgV8APh4Weod6Y07DR9Q/n5V4kOGn65kv6N/f63lA8Lf7sp8QPX28s1HY964fvcB6a@Ldx9Nyyct7nWp68da24dp6OOltdtrFO83bj68Hf39zMGvwxofny//Ao@bh7Qex7/dH34c9@GxrQ9Z/HZm5H2Eehz5Pml9fdTH5/xDFq/z7NfRr/YH74LvniD6AoePLgzcZfFqGfHD00J3mdw6KHDz0vJf4fTZXeYP@b16rAfPb3zI6kdQ@Gf5fC7SZ8dC/opof4nf63WzGzw/2l/7kN9HWx3/St63j0d8ulvz4Rg/jzI@un36I1HcfBPEe6/9vo1442r0X2HzyQrAtzd7vXo93ZsrIG@/upUs31LcvMPxluT9cYm33/9@YOPtt29vabz97tbdjN/QN25kvKV4dw/j98m5dfviLc3rOxe/c791H@K3h3hzA@I3@I07D28pbt9y@JDm172GuVJ6Ejfy5kmUhe1GfhJ49sgTf4RNU9T/AwBmT/xH1WbAf/2vkwkWMc66l9bJSh3fgmyloJ7jxKfFkNJOO27sidytTx3Pl4XTdz4PNCKGTcddW3FRZ9Utik71mFVHebmsFTraiqzhsIq4uagYhrNDhwfAeClB1GDXLU4YurXCaYb0uyGis0PR4Fpwho0oXM8/e3MpBj5fdopKigNjmJaLpyastfbKXB5FPVtyOb9GMiPDvWAXABO6NHuRileQOWzielECzTKGt7BPtOK06nFc0JMg8eM6qIPwgLpShw0NAqSYt5@K9UI6QNuuInmAt6GsQNdHEJo6@Ljv8XD29MCAJ6BA3ZULDHHfBpCyyrICgJgVhQ8tcRgDVtjCCeaCYoGnbg2pQCs6zQTwsYv4vmGnIU4F2zUjsijqMKesKVeiS/lSdpj2FrMQcULEA4taGoGx2aVVV2EnbnGRF5aXoUMUr9s9t1bAbE4loJeauQkx6wuK0p0UYPrKh0bKGDmAD7ZUivXGEgUboOy3AYYJKJzha4PcZLCFsrhRrdTVuSrifloiRbwAYcuVsi0w5M2q23dTYGUTK4kQ0YlewC9qBFuzaREgAbkoF0AQZm0B6PhOHMpW75YM6KxLUDwaUtdd1ueMaj13vasIBhFM4hhjnK6v8a5Kxy1midQuM1ceHvhOjawJwG/ETAgAakkvOkBOY4BdVlUwrpkDgJhNIHtTtd2mY@0vpf0Iu67QeyWwjheizEiIc3JW0dqsMGVr08R2USJI1lnoggtkMasSbi24mExk1HgmASCm2EnZgKgP7KWlUg/qRoUPFHo@RSRpbQzaavYScs5lZV9229hbbU1LZgs6iBYiV2/FLkEdvjE4dVPVU1khIBCQ26mGImAR0Fsdi/Za1JP9ACbGog@Aph22qR6fKdzt2DTPt/nOoyRgwbFsvBV7Y7/Kl4IskEvWn9anzTGYHWyxQNkttxdgLESyVs6wEVtznL4lGuuMS8hithFtPfEsHAhAZ7qHXBCP0wUG2qlbb/xRgyAHIdoMGVVE3EYxyMZQDo74dnnRuugsr4FmIXkTgbvsZd0Vu920Xvq7DS2spUjXSUPW2aToBmm1EJfxujwShQeyp5MbppzBXpZyuGhiRAKjIlwFUaFlo4YTycoQR5P1N9IBVUTmSDC9kZdig4nmYmsL0motSN2GP14wDiNjUWpHZ53mIW/0RyNYMD0lCt1BYNZWO8YbhSWETlzLK3I8JlhsrAd3wjhyDOKQ0b1zF/UiGu3GkcVQDDp2C4aCd9Bp17WBhYCydCgPK6BCVhRzEEXHdpl@CFiwhPuK9qnleQsHVbpcHQRNRbsBGkv8sGc7Rgf47YaWcAseL0XqMtUJH5aW2Bw1wROITbgqN17KTP5CBtbWfsdnnLMSuRDzMoUJdii41rbbar@Qhz3LLnaLSCM3My2S@jYynqYG2DOH/FKpNIUfW1zWjmgAqoOzkoWKyrl1IVkWsNK2JxwlRqo@LMr@GJi@tGVGGlAonLmMDs7JJitCPpFME4LySnDZr/doaazVNUNhLbLpz0yxEIAmRLnNbm3wGSLEtQ@qEAu7BssEsdHvl8vDcYliJBDL4rQLNCMroKp0xcxFGDMvMkDYXiA8O1TpxhPSwBFbeW02GjCJSryHV4QfejuJh1QI8jPURQOxV9PdKd6pQ2XUEWDgJcoMIH1Q/NE88dTpSJ3TLFicTmxwLgYcOO@nlRZZZy4icoMrKfOsEuyq7EGOoE57aVpocFfK5314FrFJTRrDBdhUUFrqLJpBJ9ThuPLP41RvsiMmVhARyUtzGmml3pe@69CKiF26Qsa9A3TWdPWQgwNaoQKdVaDmGwdltdEdBHK2pE244tadGo0ExGid7xqTaTvUwPcQ066QIJNFsUx6oOjn2d1khm6keyEnjnmsSIhoKhNUr9BF3InHYybuggAhmMixEvaAqLxV9RLYSV2kBL1yrgacasesmyBXVELQzIhzQzU4nu16Fw4RQFYWbHXyAavaBHBF@kaX@girSJ7QGZhfnhOMNlfgwEjBvkZO3cHV1HbvV4dxw0EEIBUgYuKCnZBwDCO6R@Ix27u2CTBrFjfjwNqP1cWEyS5VUToChJXgQJvVPFlZvsUAYagkFBVhHdBGtDltMrpdKaaB6/uUOR22XJf7mr6chkRYtZ63AYgCq7pkcxGDrVStiBDx2AIWMDVY6CvwdJZOrFR5WOPEa8TK0Fav0UZnFNTP8FgR8UuktdO6ZS98G4Pm4Fe@dMBbtBJhP87a007K2PPZ1VEotdHF0sV24tRB9TqEac9RzyjYnen1wdSDssYjke24elVaNBAy4KbCFh1UEfp66Pai4ELOagow2q8wOeAbqULJC9tZLBCnCS6B6ZmpDFQd4Pq03vFrcXHyKd5c7nLNYGyoh9waIyzEHYCGbQt1NBUTTyra23p94a1QpcU8/uyXxYI9GrDeN0GDncUIOQPCZs1ZAlIIOd3bS3DVeKFThKc2DJpujhVJsu94AnD8hFXNCOXZkcIdrQ64CbgEaiCYiJxt8RxcJwAZ2GASLPZYOdDSHkt1ZTtkG747@T7oYEWQCdtgEEhlDyEChxIswcIiuUAC3vWDM9pXmbnEN1QENCXWXSac7RwvBqJRpDH2cvAUrGm3FnXBO0wP6gmCswIUWwvfUd3c33AukJSZv6RgFovLfdfTODSh@CbQ0NzDaiIB4MAFeNxeBBVz5rLm0AXrI@F4NS7g0mGcpADnk1BmqpoolXwM9ovAPC7tae3r@WavzPFnttVS2otSUAD7rAZTtGU0d83DntpJCMQ3BYwK@04Ac7gUAE@2wD0sZoqw8dF9xvpUNQxdt006MMY5yEPmmicDGtUBGyNG/QHNzViBQDj2Ux214WCZ8c0ZSGHyADsiUDdyFsCJiXl6nB8BAzDtcikeRt9ETScLqCyEFHQUfYdeiq6/nmMrPqBLb3/cuhIqdZSFmsPUHQG50uUuJ1123AKOh7SuChJrvdquwwYIxCpn1AVV2E3nL9RFBlHZ1qkqzytdHMY5dJt7@2qNOztBxjAUqbpMB/HEEzJGXYudyayDI3CIx/qM4SsSJsU@aMUBSJwLq6DdeR3Dm6WGIog@Pxs7wwoWZ9pMd7GeI4h4teQBHPIoVFzScopnZjKHaAfx2lWS467pNAwsNr1LqtAGh2Vsue1U/FATE8a6bLjyiIDC4@U224B6nYDQFtqNeUKwXVdYkRMRc3bau4WzMiJouRfxBRHYOhADDa90CAEQYsqj@wQJwDlUdE49iB48ZxpJHANKBWjqnIV6Isi0rvbNqAEbd8W49pIJiioZmM494myEdicQg8h8vQHgk9MMJLwv1sFynKs1dLZQNN6JS3tPyDtA79mAJ2wRomAGlZ1yExwgBe81EcP7w04zjTAoJddfHNbdeVhtqELPY3xrTnEabLLlqhQvSZHFXqgXsFvuDsg6QA5BMLENN4EHv2PixR4Q6LHtIaDBZVxW4bpvgX2HbtdimoGrvoNhgjMH9WJ5Pd6sC3QBK9AUonLQuDSIHhZqd/TWegB0tY7JwDngAUuwO5Q4rAcyHFYwkIZwxwBrCjZBFIi2c5zMMIkatuqsEtwpmSCdE3QNoFEnzxEPkWb7EKZ2Xc213MHS9/1w1FE@E5Rgog7BSZ7bpngkRW@R@6AHUg2yA2m39c01SbEx2VSwNeqQyMQN0E3r4wLelFW/Xk9bkKO3LVTioioVaH5oz7pkRntAZXcDRzZkd96C8RFPd6EBlJstBJOtdvR1kUI0Szvw5Dk5L8HGr5PzbgMs1uw0sqPfh@o6Px8WpHDeO0ir69FsmaXYR0PWFG65iXu@FtgRHNcpvHRAN8Nhttu0Z74XFl5P4BcdWnVwuV9jOlurJwsWAEvE6HXH8es51OoGtoHKGPNrZwkiiE8Re48J1NFqS18X1ADpZrUFToXaeLZScIA7AuIJ7Eagb6k8Q8xsPYACjMAE7Kwyd25G2HkSM188r9cZR2GdPhfdAaLKTrfBVXPh48Ksgh2FzS3ThqEMwIUolF42YzKse5SURseME7zrziZKaXOHlcceInqtccH9qMEumGcbQMWv0bxZoOge8xYqyppo1wKbSiTXHuOhFw9qHHw1p4IAlnAftUB3MQTJtPSzXDzgKjC7LD5w8HYXStSyC@A6G/WiT44TBfgjyhE7cW6W4KxhcTWgJgQIehquImNjFshS6EiHRR28g2tyi8jLJt2P1gU5G9wcrVRrjo9HyuZo3k3WXZDzIrL1ZaAQDzq@9IFJ3ZnwjloDxx6PNFxHTqSyEbpCaU5SLgBZsMbjzYqJ6pzkggxYatRp8oS6AyZu2WdcjVeoe9mvEFu9@HNIFbwjVYPAUK98Fytwd0DFclNr0@6YBWwxN56HzlyvKX4IrAAbAwhe7qM222cOtmIxDDABpJKrrg8hYWvk4lhZ@plskstWnZbwRUesotaBfR6cWwA4lnC8ZAFAGROkmGiWTvM5qzMbd5HwdS/VR6jExNoI1aTdocYSy0Kmn7svZHHK9b0Bh6q7jM4X5agfCK3k9ownhLIwxEQ6hE266bhDo9S8zIdNtydxm/BCpTobRCBZknGuJlBTLRUYqpNsV/C4jVqPgXCGDQ1nGxGtU/BtPgjIWcGFPQQT9X6V1NwRPF5aliJPh8bCQ0VTksjzwrnShEk6arXIGV3YSahsvUcIiHT2hDNtLyf@hFowZzBAjC8KCN3u@YWPwBw3ioeVHe7b4UCWC2lrT3sXkRYybcX7OiJ2jF1OYChZhN4wTXS8IHYroO7mknj@woECVeS9FnY5MlVU7KTW55TUL1INOjrl99JKNSIOYmOqNOYSMBv366T2DyfbdTUFo2MGNuU1u3BkmDfbhQFRlZoYRUwje2qOWStohCzLW0u13Dur5dEx1@e61ZVKW7qgHeQd4erR4CudtiJlfqx5vCv0oyTnI7/HS/Uk9TBDcVyUGjymZemJ9xIvKobIWIvQACWuV5xA6GwPxBBHwgZa1b6zJIDLkliGK6GeWwiSRo9FVK8pSfEjr2u2/NKRw34uYULROA@KwVBgQuoOF2@ZC6Gj4lwmU7EwiGDLD/Kk8PtGtlfsejdOfUobqybHa7kZjvgcN/CRjBDRXXorqclkpJtMbFKIJZv04qGG/BqDdKXe2u3Kh8za2bq6uAQdxMLlOCsVXjms46im8c46BzJ9mcumJuLJEnAsb2mQIL3kVDTydutml2iBtS7y5ahKRy3q7R3aCjobUDwl@2Fzbk8XJz6X/GK3NwLz0l4kX0UArtD0Q7XX6mk/z90JAhR/ovtzfKYny5JHjRWVlMF7zttz9c45aceTjbWbE1IoPQyT@dlObViY8tZab@XUOTN7WjSFxXkpRGmtSqc6iWmNXXrVMljXLHfyijSU5OI8Alq/Wp7WYaW0XMxxZ6yFNV/QyJKNXIDozb4mzv6QgjI7WISJJagEJmPP9jQkHuzeM7h6SMoSPV9gKDH3ORpcGMfkd0wdNvGYLk91K0My3kVanmLR6gSOpy1g0u5yKQ8@QOWT1hxVDjCbnb6kyF0rzPF5twGLSHE7EuqXSZDKnaD5mbVbMRfY8MKlGctUcFzXgKMhMNBoKAGNUQkV@wMkSpi4l3nM29bwWG@SntwIyGlxXq1gDbNNHQ1PLo0iFAJSx53ZOJdFuhwLPu4hdqeBCUzQpjDSyKKZi3o56vEDr8Et3xkGjbiRUIoMqTPnFZRyYyaRvRNxRyg8uvIJo@qFulrKx9JiuPSQXaDwAizPQ9HsJUYQ2lIVWjdwYq1YFWlPsZxtNDVt1WrncCpw2pVjTYqaYGorvfc2ohdQ7KXclaRKzD3fpuCqERIvdUxOvLweMPrQIkxx3iSJ4S40b7QEV1tZjpxHArKz9Jpmx53GFf5wLBYRWIVetx9zyxzlHFcv3hzAJZ3CqApnws7oVzt@lRiTYUDCoXKUs25Y@ZxdVpMCbfrw0tuhv4mcZqvFJO@WyEX2D2Qal0cmKeEoqxdRvVsUjTZb6mHk0ML2T8W4YPVapYgptTxYQxY1d4ZHqpz75vPKsMu2aQ87jJzME5EDSsoiHF9sL9jo9WDW1HPz50iQvTJtPzmmhtjFE7kJiYiWaQIqFvseulQuhy@gNKe5KFQaWEfktKV5ajkssfaYtXMyvGRzEQRs91ZemsMKiugIJo4WBDdI3TaaoHiL1rdWw2lkZ4tL@eJIKALZkeTSJU1V9kawTyaOjnOHVHIeWWYnFSvP57hb8qKxPl1Gh1cGHZp2rK6eESPmKS@m3RUqDeWKPqKHuedfGQVo73aE2yqb2iTwRtaidH/Z5Ge4nWNKEjNzzbGQmhOzPB5rfjQkhBV6yWPPc409Z0rZOKoGc6BEZqQrGlFSWo4AmiwupziUuUaq14nokuBcsacwS6zUtm7BtsWySO8rRFu09Vpq5hijFahyXJpDDVHSSRxrezfVdbSglHNL030yKCaKYnHq9BljbTGuMb1THuYBZDZTDpsHEhsbtEkFVVvShHFk3HoX8juCjABJ8y4pJJ48tubpqo1lXTmCE4Xg1Y7N8bNLsEkOnuuDej6hXTmn4lG4WJfS0I@gBNhCTF4W1m6R7rBQTJDmzLdIqO4U5ZSeSCZUMtC0V6KcHvaJd5FxJIXOy5VNt2uI7txLK09pYx2SLWoHR7jvoRNRjxfMzhuiVjr@rKH6sayWmTYniRrj/EuWX@z8pEcBG8LWfoHuPN2GSrrNe5hkM64QIJ4hNlkizvU2pAnHMq7Yc6geCS2jqjSBIEtAdOh4KSYZgjKGCNeYKfPaKcu4fURlBzslM7dHdV4fGFddgAkHHU@4q1N7Z0NUhJ7wVhbPbW8diistH1SWKQ8NRPau76XHzvFVT/P6GDrsUhCCGhbuhyk@tfM/Pt5u1hoiorutIK3VVYosUU6FZJeXh6HdKpe1lGWXMFS1UOgwKsJTNY/slB22h3oVHLaMbFO7NRfFfbbkMKOwzoAVt9jm4k/ebkutGi7Wj5pQ9PlpSV84Z4lYpDfKkecGvBsThtunnV/FuzKuXdDV95WZnoiNkc/RWebnEKRoEXxRbfFIqy2o9MZkqXFABbS@Z5z2vO/FM763Ee/cTsFubqAPagbaLrEQxfwAlZQV1V5ouYaCTj6/dsEpumhsgcXbKgcFbKXr0zlcbsudoYrIzl6bK7nQQ5vLsuYQupjJHQS@AGSo0@ETLPdoStdW2DKC2AWVd7RFzhfOYSWeVoa645mWVKYxzk3bkIFyMVhzzBeWTbxcmhGgLJDGUrFCmft4oAxRNETtE0Ds81US2Qenx4shN1CWO2aRDIf@HCcA1@agDsKr0ewgcsj12jIJOBYm96jWoLER@@UeBs89zzSlj/GuR6v0gWzWEZywTkvEBCtaycK3luwxuji1nACmk2noAjqxcxTkzHBn6BztH44@vGbojucccb@PSwuRCs7gDm7UbE6H/To@gRInraHDpXHahd13Z9WFosvimKTbg6i15wEhcUmRWokMfXhEGA1iaagkST6hyoBAFlCiiCN9FtWOBwdZj5NiQWcxAdmkhNsDNI@1wPTJy@bsn8dFER7WNbhQktrqZhuZwg3dt7seOuIiNjevjk3VrWAI5JnnxxO294ycLud@fy6HVcJSht44aMOC26xCJwf5ccg0p5hbPtRclZd1OjJ8vbGUQABJzTDk7eEErYEJEt1K0lV2iS7mErA5bksHc3ZLdu6@hIKn7KSXtqCi0uWyzw0ZF5q5eITiPWn36znXFBZ6Ud1o4EpXSIv4DExzKOZM3asXJz3u6qzOcU3K@KbpDnKTrBBGdWWfNHfL@pDrxzWtFcJxq7FdXHFNDntVtxHWpmFstyy5rDbhcdXClht6q5ALOg/bycR2YR24XT4FDVc22WXPlKa8OPrbulZg/ZSKuX0aS75W4WBotseD2@IrKeasjclkikWnNrOBfHDYt1Ttzrl/7n5PhWD6sD@d5NHmt5exWFuUJDG0v@QFY0ANipk77Gwztqxhipo@7iF00jHBxaPpdIRllqUxICzDaK7n5dV0cvTALQagr8teUnN76UctY8V0lTrOHKhOjVV7PDiTcU41uYy7kKqCWoaQtbeKOCG1xMdWgUBJayNTYsEht3MZgqnRyU1OAr/Ni@PklSZrbTSSbWwuZAjk0h7PZtrzWy9TQ0ZIVqsCZiu/apkduE3N5dx7TeRc9zREqnL8lsrbeELqpTMdIeyEMEbM@doBSklY9/g14Zm2poNNI84V3GCP8ZBCIEPSDlyCNL8@CVR9ZCt1a2DJObXpSo0FPRGxae55ikpxVrvkbJHTqLCEO8fPI5xHZhmxpGax8nQaGqMtWoHok6DKSwkt@FWuqE2wYlZL3g36pEiP4VJutcVBLy5e6R3oBahorrFrrHED1bG8plUv2xwuGSOY5WIexZA7KaJqqhUYDXS49IhytDLWvU@DvKyz2kjItkDYfbmZcqYSzoyE0Rx4yNRjz@z3l46JLmXSJ6opCokKF9s07Hn3ECS0ydpSNOmozYk1kgqae/EjPU390l2BLgwyaGX6@RkKsaVBXw@oXOBASM8bQc04aCK2ir7uBd7JkfKygi396EqpG1HkXALmpoGqzj4/XWItjMRBNjArctw@TuccnO12qq3xNAjvYQhIy5XsV6M/nhMLHZtTf06p7LKp5jJViTWX3@ldOMxcHWOr5/IAqtpmUktOXx4FW89Rfu9LWr5b6UgGG/jILDRRQsSjLNQTfKAoZru1YP3s6twOoskVe/ZOuHjCrJOwcoGjrAbwMksWyrE@KOyQErypAqo9cdvYohYHUYA9YSPn5pyxpo49nYcgPVWal3CluJuMHGvCyeEDZ98Q5twlXlovA5O96VdsndsLbSc5HquGsQjv9o4sHTRuu7WzbFdw3EaU5SJupmM/SNKi2OSgiDNLvK7JIj3rxGFrl7W6R1aO3OJAFrUUUUKb9HyJ@VJN2tmE3CCjk9Tii3aRDlBFbngLCvMobRFR68O5JqJDQ1c9xRJGrh9ZPmzDZUsTZXXxDuYcGFdlu6MFgs@OJ6o6oYE8rg4dVsf1aYdaO084HXfFjnAQByxYlvQRm9d0uXe3y8WmgfBNqPsdbuq8w1pO0dCecExtzr1AtLIVdFywI81PY@pCHQsyVQ5TRwiqMWtvrI4@UTWFeBriFFwHdFgrAuYcjcZaHbQD38cIf2qYPX4xJCMFe1hwymCPktKxb5lCg/HqiBw4fRWbNsLs3Fr2165e8NblAEecxJVMUlhCHyU6lvR5vu9jPQUX08WhOeloLnnwjNnbXD9EDa@gR/UUHpsi60szjY9lc9rxc@TFF6JUMD2BuNCRKmNTwN2khNKjtBRAWGEdu7JYeC7LSXBlH/gyKOiLEaiQh1rScVgPB4tEfc@JhTUccA6rb@xRVPHU14wGmhyIS@oRMwxmpRTNBY@PwtnYxrUnDbl6ccNTPgx6UIGeA1/ypQK2UcQIpMHma@oiH1DDG5QlRrp8Q/ENz@RjljhzHZiONcKnHkPkh11bk5x/khhQO1f7duFSeZN44M6QETGoho1ZgLzJ96yqcA20V5uhxHYDRZXWZmj0pF4MxelC8wVIoq7T0CDjUsgeMoiCGfHhwqEUR3FmDFT7cX3ZCRNzUCiwKcPOv8jqRe0GZSrUOsHIPg2t01mnNwvFJaJdH3mXnI@4xdwL8kgH5YZYtcp@btFJJ8V0edQA5nLK1X6M64x3jDTcOco@HeJVMw6MwvFLGStXEzEczLSb7QsySV2KZZVAypoac7qTRrtRIIOjC9JdenFY6Mlu0YN2vgl0aI5DkXPZSheVNegDd6x9dWB29MXBL/SuVI/FKfWA1VwSqJi3y4eItE4xmjuogqsSt0pSHT0EjReFiGAQpN/PToCTy3Nsqd4uuKycDaiuOExOZS3dDbAoTb2xkvVDwUg6FPJ9JKtks9qmGHsst2U1Ygk3KARUFfacVJJLeMIRY4XsQ5oSXPEI7QQOZKPo3KW1pm@WIKk0wkiQQS7GyuLgUi6yLkI3hPwp1hZgT5WqORvhPi3YgGxr/RwgRbHCD2O62ByhnM@lkFcha212G0kxtKiOVuYRBxekjO00KJfYJPJU7VxkaJ6aRVkdFszKWPlz/@J1DcYPpxjaWculg4OdpeSxbfhwnzXAtq0ISMWNEz5GLj3QHMcZR5FII1VdEylpaNtuodGaUHIIz6WL/Lzf@QJOHzQJ9hspTKLzJqC5w9okA2dFeWtKo0LMtIqRSxBFSebifKjdfm3KNLhNqlxai0jNaJ7rmU1D0@uLykVVGhuOFRbpxuItIx2xHiJpjtzrvErlsXbY@Vup9WWdJyXmZPriuaDVia0Nh1jrXU8kQ0lO3bZMGGLBiOH@CBATnCDEop9L2YrRiGDHFDhDJ5yBamgOLsHYbQweKzgeG1pId50g2rIc2clt6zKFojJUuDrsK6W8DAMA1VtWSydjFU7qRHGMnBMoN60W55iBcSLetW0PbRSlzhVIqbWGOK23HCQk4V5gIstKhGRdd@o@H5dFAcKsVZE4wk7YwKFkFw9gUZGDkC81YQNbm7JIzT2pbPcxzJ34jZSSVAgJPrXTFKI@GTlMWt0s2SAfVOk0dsedITEHx2/h2MctdJsbesq4bE4zuJ2r4rZArRZlpN0hHoSJ8M8NaJntielSatAzr0pKZk1MO0XTU3qjaDByki3@SMTboYiwOQwmUkEm7plpWMvTkOkITDkaDYTGDIi3c5IK3dqi0Wc5KgCXpVa2i3PpJEwzCSdCWgs0WXus5U@7TToXhkh28JbsQoMG3I7F3Ie0i88d9guVqZPSJwJvtbboJLYb5sQz46VkPNuvzwPIEXtVj8S5jk8dtwrXKxcy5eNBSMfT4eipElOZFJmYjJ0nJMJne/4SXiZKTo6Ja@hhWO@IopXcVEl1Yo4Q8GkgsQsi6i2J2ai/czZ5dcIgCz3tdi2gMWpt8WurECUIEqxwlmLjkmnGJIdOOcyVj2CgRqgSTI@kFjJZjgw2WZRqcjWHIV2vHJaQ9WBhinIzDCZytKEiiI6FV9cgMeigZ@C9Sczh6LAvDlGEKNiyRGDaH2D3vCnbIpMoX8nT1jt0Pj6XyceF7jcaseNnR12pOB1bC1ANXFIaMq5qkl2zNVAw2zfk4nRa9nvjdOiBScpYOznSgSHUDaJ56i7bQ1COxVKOjtbudBlrS/PC8mKNC2xYHmkrp0MqOa2ocs4gKKf6Gmz1rDHueVXZapd2Q5fRgvWPm1INK6Nv3XY32F2rX0haFThzjxRKQ3mHw2Vr9jnvsaOE5Jx9OLN747gnl8VKOsBBXDTLCyTy/iWCR6cwdetihsBGAK1EX/DlqjJZMk7E3anJtmtxq0kbamcA27weumYO/Ltj2pezm52PaacltLDJnFgS965iHXvDNdq0lY6eHvGdABmlakd0G/O0n@PHY9UHiMGyy7gLuINBqDnT22cOtIipE/alktlLtdq1PKTJ5zmFnNJdklNcj2iyS13Ank/UCA7TaTMZzKmX5djSFHJyl5Itn9qQWRowvx933GDtbbAXVHU58d1qRe2Wos2Ac8sAZttaGVivO3Aeu2w3AQA3PQphZTAH3pVb0hdgP00QBMyd5ZRdrktDK4Sgg4sfbEW4B3AuiDpzRHwzwCppu24TD0JYIAgSoBlFAOtSAHMWQA/88cetV8L/z29vwssrz6/@fP/2ve/ni/@MMu/lhXp2Fdl/5k2V/3nzNYc/7sx8P8fu5Vnz/O5CwP@aR/3ghP@t16p98qK0m2f32yzq/Kq@vqXv2@H511Tfz7S/@ezXS@3evXrp@sGPyzJXsV9dovh15eP1tfd5nvzrHyK93tB8fbv1f738Fcgff9fx@eU897//4zON/P7e9s5PPpm4p99Fv9K@uiX3TegPpPgP4I///M8P/7jb32shP282fGoif75@P@PPl0LfvP7x/R7Hj7fRvrwxLb/ebnh226RpK/vPd28QfTXmbxfTfor3/6iN/tn4178RX41/vn6n3PX/35l@aMRvXpv1kRX/mUQXv37@MeVv387x@sr0LUN7@1EaDc31Sb7fgqn//R//Gw

suggest(commercial_plan, [wants_order,wants_recognition,product,indumentaria,otro,allow_sell_workshops,physical,global,dont_allow_association,wants_money,have_fun,strengthen_your_team,travel,service,objetos_de_cultura,allow_sell_talks,dont_allow_talks_workshops,physical], [has_savings_or_funding,doesnt_have_account,doesnt_have_credit_history,doesnt_have_passport,university,alone,doesnt_have_balance,doesnt_have_followers,has_achievements,has_contacts,tertiary,has_partner,has_balance], [non_social,extrovert,disorganized,independent,young_client,likes_travel,shy_and_afraid,adult_client], Sugerencias_final, Sugerencias_mixtas_avanzadas).
*/
