suggest(Actual_plan_context, Goals, Contributions, Identity_traits, Final_Suggestions) :- 	 find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions), find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions), find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions), find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions), append(Goals_suggestions, Contributions_suggestions, Pre_partial_suggestions), append(Pre_partial_suggestions, Identity_suggestions, Partial_suggestions), append(Partial_suggestions, Mixed_suggestions, Post_Partial_Suggestions), extra_Suggestion(Actual_plan_context, ExtraSuggestion),append(Post_Partial_Suggestions, ExtraSuggestion, Final_Suggestions).  
extra_Suggestion(Actual_plan_context, ExtraSuggestion):- can_suggest(Actual_plan_context, ExtraSuggestion), final_suggest(ExtraSuggestion). 

/*suggest(Actual_plan_context, Goals, Contributions, Identity_traits, Final_suggestions) :- 	 find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions), find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions), find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions), find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions), append(Goals_suggestions, Contributions_suggestions, Pre_partial_suggestions), append(Pre_partial_suggestions, Identity_suggestions, Partial_suggestions), append(Partial_suggestions, Mixed_suggestions, Final_suggestions).*/


find_objetives_suggestions(Actual_plan_context, Goals, Goals_suggestions) :- findall( Suggestion, find_one_objetives_suggestion(Actual_plan_context, Goals, Suggestion),  Goals_suggestions).

find_one_objetives_suggestion(Actual_plan_context, Goals, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Goal,Goals),  valid_objetives_rule(Goal,Suggestion).

find_contributions_suggestions(Actual_plan_context, Contributions, Contributions_suggestions) :- findall( Suggestion, find_one_contributions_suggestion(Actual_plan_context, Contributions, Suggestion),  Contributions_suggestions).

find_one_contributions_suggestion(Actual_plan_context, Contributions, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Contribution,Contributions),  valid_contribution_rule(Contribution,Suggestion).

find_identity_suggestions(Actual_plan_context, Identity_traits, Identity_suggestions) :- findall( Suggestion, find_one_identity_suggestion(Actual_plan_context, Identity_traits, Suggestion),  Identity_suggestions).

find_one_identity_suggestion(Actual_plan_context, Identity_traits, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(Caracteristica_identidad,Identity_traits),  valid_identity_rule(Caracteristica_identidad,Suggestion).

find_mixed_suggestions(Actual_plan_context, Goals, Contributions, Identity_traits, Mixed_suggestions) :- append(Goals, Contributions, Pre_mixed_traits_list), append(Pre_mixed_traits_list, Identity_traits, Mixed_traits_list),  findall( Suggestion, find_one_mixed_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion),  Mixed_suggestions). 

find_one_mixed_suggestion(Actual_plan_context, Mixed_traits_list, Suggestion) :-  can_suggest(Actual_plan_context, Suggestion), member(First_trait, Mixed_traits_list), member(Second_trait, Mixed_traits_list),  different(First_trait, Second_trait), regla_valida_combinacion(First_trait,Second_trait, Suggestion).

different(First_trait, Second_trait) :- not(First_trait == Second_trait) .


% RULES
% TODO Revisar que las sugerencias de todas las reglas esten almenos en uno de los planes (excepto la de error), asi no olvide agregarlas ahi
can_suggest(commercial_plan, direct_marketing).
can_suggest(commercial_plan, logistic_association).
can_suggest(commercial_plan, international_contacts).
can_suggest(commercial_plan, outsource_sales).
can_suggest(commercial_plan, start_selling_followers).
can_suggest(commercial_plan, talks_workshops).
can_suggest(commercial_plan, trade_show).
can_suggest(commercial_plan, embassy_association).
can_suggest(commercial_plan, international_association).
can_suggest(commercial_plan, brand_association).
can_suggest(commercial_plan, politic_mayor_association).
can_suggest(commercial_plan, influencers).
can_suggest(commercial_plan, hire_business_manager).
can_suggest(commercial_plan, work_near_clients).
can_suggest(commercial_plan, use_CRM).
can_suggest(commercial_plan, meetings).
can_suggest(commercial_plan, samples).
can_suggest(commercial_plan, target_massive_markets).
can_suggest(commercial_plan, carefull_deadlines).
can_suggest(commercial_plan, sell_talks).
can_suggest(commercial_plan, sell_workshops).
can_suggest(commercial_plan, logistics).

can_suggest(management_plan, find_funding).
can_suggest(management_plan, save_for_urgency).
can_suggest(management_plan, hire_secretary).
can_suggest(management_plan, use_personal_agenda).
can_suggest(management_plan, disconnect).
can_suggest(management_plan, find_partner_for_support).
can_suggest(management_plan, plan_breaks).
can_suggest(management_plan, invest_on_your_business).
can_suggest(management_plan, aduana_suppliers).
can_suggest(management_plan, known_partner_divide_roles).
can_suggest(management_plan, outsource_control).
can_suggest(management_plan, systematize).
can_suggest(management_plan, assign_roles).
can_suggest(management_plan, weekly_meetings).
can_suggest(management_plan, define_billing_process).
can_suggest(management_plan, therapy).
can_suggest(management_plan, do_sport).
can_suggest(management_plan, keep_yourself_busy).
can_suggest(management_plan, talk_partner_objetives).
can_suggest(management_plan, carefull_deferred_payment).
can_suggest(management_plan, cross_control).
can_suggest(management_plan, design_processes).
can_suggest(management_plan, monitor_employees).
can_suggest(management_plan, explain_how_to_delegate).
can_suggest(management_plan, consultant_or_coach).
can_suggest(management_plan, hire_experienced_employees).
can_suggest(management_plan, organize_billing).
can_suggest(management_plan, arrange_bank_loans).
can_suggest(management_plan, arrange_passport).
can_suggest(management_plan, take_time_communicate).
can_suggest(management_plan, talk_directly_about_problems).
can_suggest(management_plan, relaxing_decorations).
can_suggest(management_plan, digital_payments).
can_suggest(management_plan, local_payments).
can_suggest(management_plan, update_netbook).
can_suggest(management_plan, everything_online).
can_suggest(management_plan, outsource_accounting).
can_suggest(management_plan, strengthen_leading_experience).
can_suggest(management_plan, learn_leadership).
can_suggest(management_plan, self_managed_team).

can_suggest(communication_plan, paid_ads).
can_suggest(communication_plan, local_social_networks).
can_suggest(communication_plan, digital_store).
can_suggest(communication_plan, physical_communications).
can_suggest(communication_plan, digital_communications).
can_suggest(communication_plan, talks_workshops).
can_suggest(communication_plan, ecommerce_association).
can_suggest(communication_plan, investors_deck_ready).
can_suggest(communication_plan, communication_association).
can_suggest(communication_plan, outsource_communications).
can_suggest(communication_plan, communicate_methodology).
can_suggest(communication_plan, care_about_design).
can_suggest(communication_plan, influencers).
can_suggest(communication_plan, use_achievements_branding).
can_suggest(communication_plan, guerrilla_marketing).
can_suggest(communication_plan, press_and_magazines).
can_suggest(communication_plan, client_frequent_places).

%Plan legal 
can_suggest(legal_plan, create_sas).
can_suggest(legal_plan, iva_90_days_delay).
can_suggest(legal_plan, travel_documents).
can_suggest(legal_plan, accounting_balance).
can_suggest(legal_plan, handle_payments).
can_suggest(legal_plan, tax_checklist).
can_suggest(legal_plan, mercadopago).
can_suggest(legal_plan, public_accountant).
can_suggest(legal_plan, money_really_took).
can_suggest(legal_plan, salaries_check).
can_suggest(legal_plan, cross_check_control).
can_suggest(legal_plan, ensurance).
can_suggest(legal_plan, register_brand).
can_suggest(legal_plan, money_requirements).

can_suggest(marketing_plan, sustitute_products).
can_suggest(marketing_plan, pro_network).
can_suggest(marketing_plan, study_competitors).
can_suggest(marketing_plan, understand_customer).
can_suggest(marketing_plan, understand_product).
can_suggest(marketing_plan, aim_premium).


valid_objetives_rule(wants_recognition, direct_marketing).
valid_objetives_rule(wants_recognition, talks_workshops).
valid_objetives_rule(wants_recognition, meetings).
valid_objetives_rule(wants_recognition, trade_show).
valid_objetives_rule(wants_recognition, press_and_magazines).
valid_objetives_rule(wants_recognition, influencers).
valid_objetives_rule(wants_recognition, client_frequent_places).
valid_objetives_rule(wants_recognition, talks_workshops).
valid_objetives_rule(wants_brag, direct_marketing).
valid_objetives_rule(wants_brag, talks_workshops).
valid_objetives_rule(wants_brag, meetings).
valid_objetives_rule(wants_brag, trade_show).
valid_objetives_rule(wants_brag, press_and_magazines).
valid_objetives_rule(wants_brag, influencers).
valid_objetives_rule(wants_brag, client_frequent_places).
valid_objetives_rule(wants_brag, talks_workshops).
valid_objetives_rule(wants_money, find_funding).
valid_objetives_rule(wants_money, investors_deck_ready).
valid_objetives_rule(wants_money, target_massive_markets).
valid_objetives_rule(wants_money, money_requirements).
valid_objetives_rule(travel, trade_show).
valid_objetives_rule(travel, international_contacts).
valid_objetives_rule(travel, update_netbook).
valid_objetives_rule(travel, everything_online).
valid_objetives_rule(travel, digital_payments).
valid_objetives_rule(travel, travel_documents).
valid_objetives_rule(have_fun, trade_show).
valid_objetives_rule(physical, aduana_suppliers).
valid_objetives_rule(physical, samples).
valid_objetives_rule(physical, logistic_association).
valid_objetives_rule(physical, logistics).
valid_objetives_rule(physical, carefull_deferred_payment).
valid_objetives_rule(global, international_contacts).
valid_objetives_rule(global, digital_payments).
valid_objetives_rule(global, everything_online).
valid_objetives_rule(local, local_social_networks).
valid_objetives_rule(local, digital_store).
valid_objetives_rule(local, local_payments).
valid_objetives_rule(digital, local_social_networks).
valid_objetives_rule(digital, global_social_networks).
valid_objetives_rule(digital, target_massive_markets).
valid_objetives_rule(digital, digital_payments).
valid_objetives_rule(product_and_service, local_social_networks).
valid_objetives_rule(product_and_service, local_social_networks).
valid_objetives_rule(product_and_service, press).
valid_objetives_rule(doesnt_know, local_social_networks).
valid_objetives_rule(doesnt_know, local_social_networks).
valid_objetives_rule(doesnt_know, press).
valid_objetives_rule(allow_association, brand_association).
valid_objetives_rule(allow_association, politic_mayor_association).
valid_objetives_rule(allow_association, influencers).
valid_objetives_rule(allow_association, communication_association).
valid_objetives_rule(allow_association, everything_online).
valid_objetives_rule(allow_sell_talks, talks_workshops).
valid_objetives_rule(allow_sell_talks, sell_talks).
valid_objetives_rule(allow_sell_talks, update_netbook).
valid_objetives_rule(allow_sell_workshops, talks_workshops).
valid_objetives_rule(allow_sell_workshops, sell_workshops).
valid_objetives_rule(allow_sell_workshops, update_netbook).
valid_objetives_rule(strengthen_your_team, consultant_or_coach).
valid_objetives_rule(flexibility, update_netbook).
valid_objetives_rule(flexibility, everything_online).


/*para probar plan legal
valid_objetives_rule(wants_recognition, iva_90_days_delay).
valid_objetives_rule(wants_recognition, tax_checklist).
valid_objetives_rule(travel, travel_documents).
valid_objetives_rule(wants_money, handle_payments).
valid_objetives_rule(flexibility, mercadopago).*/


valid_contribution_rule(has_savings_or_funding, invest_on_your_business).
valid_contribution_rule(has_savings_or_funding, paid_ads).
valid_contribution_rule(has_savings_or_funding, save_for_urgency).
valid_contribution_rule(has_followers, start_selling_followers).
valid_contribution_rule(has_achievements, use_achievements_branding).
valid_contribution_rule(doesnt_have_account, define_billing_process).
valid_contribution_rule(doesnt_have_account, organize_billing).
valid_contribution_rule(doesnt_have_account, arrange_bank_loans).
valid_contribution_rule(doesnt_have_credit_history, arrange_bank_loans).
valid_contribution_rule(doesnt_have_passport, arrange_passport).
valid_contribution_rule(alone, outsource_communications).
valid_contribution_rule(alone, outsource_sales).
valid_contribution_rule(alone, outsource_control).
valid_contribution_rule(alone, hire_business_manager).
valid_contribution_rule(alone, find_partner_for_support).
valid_contribution_rule(alone, update_netbook).
valid_contribution_rule(has_partner, known_partner_divide_roles).
valid_contribution_rule(has_partner, talk_partner_objetives).
valid_contribution_rule(has_experience_leading, strengthen_leading_experience).
valid_contribution_rule(doesnt_have_experience_leading, learn_leadership).
valid_contribution_rule(doesnt_have_experience_leading, monitor_employees).
valid_contribution_rule(doesnt_have_experience_leading, self_managed_team).
valid_contribution_rule(doesnt_have_experience_leading, hire_experienced_employees).


/*valid_contribution_rule(has_savings_or_funding, iva_90_days_delay).
valid_contribution_rule(has_achievements, mercadopago).*/

valid_identity_rule(disorganized, hire_secretary). 
valid_identity_rule(disorganized, personal_agenda). 
valid_identity_rule(disorganized, disconnect). 
valid_identity_rule(disorganized, find_partner_for_support). 
valid_identity_rule(disorganized, plan_breaks). 
valid_identity_rule(disorganized, carefull_deadlines).
valid_identity_rule(extrovert, direct_marketing).
valid_identity_rule(extrovert, contacts).
valid_identity_rule(extrovert, talks_workshops).
valid_identity_rule(extrovert, trade_show).
valid_identity_rule(social, direct_marketing).
valid_identity_rule(social, contacts).
valid_identity_rule(social, talks_workshops).
valid_identity_rule(social, trade_show).
valid_identity_rule(passion, direct_marketing).
valid_identity_rule(passion, talks_workshops).
valid_identity_rule(passion, trade_show).
valid_identity_rule(humorous, direct_marketing).
valid_identity_rule(humorous, talks_workshops).
valid_identity_rule(non_social, digital_communications).
valid_identity_rule(non_social, communication_association).
valid_identity_rule(non_social, outsource_communications).
valid_identity_rule(non_social, outsource_sales).
valid_identity_rule(non_social, take_time_communicate).
valid_identity_rule(non_social, talk_directly_about_problems).
valid_identity_rule(non_social, relaxing_decorations).
valid_identity_rule(creative, digital_communications).
valid_identity_rule(creative, local_social_networks).
valid_identity_rule(creative, global_social_networks).
valid_identity_rule(class_and_style, paid_ads).
valid_identity_rule(class_and_style, digital_store).
valid_identity_rule(class_and_style, communicate_methodology).
valid_identity_rule(class_and_style, care_about_design).
valid_identity_rule(class_and_style, meetings).
valid_identity_rule(class_and_style, aim_premium).
valid_identity_rule(shy_and_afraid, care_about_design).
valid_identity_rule(shy_and_afraid, therapy).
valid_identity_rule(shy_and_afraid, keep_yourself_busy).
valid_identity_rule(shy_and_afraid, outsource_communications).
valid_identity_rule(shy_and_afraid, outsource_sales).
valid_identity_rule(shy_and_afraid, find_partner_for_support).
valid_identity_rule(shy_and_afraid, relaxing_decorations).
valid_identity_rule(shy_and_afraid, talk_directly_about_problems).
valid_identity_rule(shy_and_afraid, register_brand).
valid_identity_rule(stressfully, therapy).
valid_identity_rule(stressfully, do_sport).
valid_identity_rule(stressfully, outsource_communications).
valid_identity_rule(stressfully, outsource_sales).
valid_identity_rule(stressfully, find_partner_for_support).
valid_identity_rule(stressfully, relaxing_decorations).
valid_identity_rule(stressfully, talk_directly_about_problems).
valid_identity_rule(stressfully, update_netbook).
valid_identity_rule(anxious, do_sport).
valid_identity_rule(anxious, therapy).
valid_identity_rule(anxious, keep_yourself_busy).
valid_identity_rule(anxious, relaxing_decorations).
valid_identity_rule(anxious, talk_directly_about_problems).
valid_identity_rule(anxious, update_netbook).
valid_identity_rule(organized, paid_ads).
valid_identity_rule(organized, digital_store).
valid_identity_rule(organized, communicate_methodology).
valid_identity_rule(organized, aim_premium).
valid_identity_rule(transgressor, digital_communications).
valid_identity_rule(transgressor, guerrilla_marketing).
valid_identity_rule(transgressor, carefull_deadlines).
valid_identity_rule(hate_numbers, hire_secretary).
valid_identity_rule(hate_numbers, outsource_accounting).
valid_identity_rule(non_profit, direct_marketing).
valid_identity_rule(non_profit, talks_workshops).
valid_identity_rule(non_profit, local_social_networks).
valid_identity_rule(non_profit, everything_online).
valid_identity_rule(young_client, local_social_networks).
valid_identity_rule(young_client, global_social_networks).
valid_identity_rule(adult_client, paid_ads).
valid_identity_rule(adult_client, digital_store).
valid_identity_rule(adult_client, communicate_methodology).
valid_identity_rule(old_client, paid_ads).
valid_identity_rule(old_client, digital_store).
valid_identity_rule(old_client, communicate_methodology).
% TODO en vez de ponerlas aca, hacer que se adhieran a las Listas para Cada Plan con un Predicado Hecho /1 al final, asi solo aparecen una unica vez en vez de por cada elemento. Ojo con bypassear control de validar puede sugerirse por cada plan
/*
valid_identity_rule(_, explain_how_to_delegate).
valid_identity_rule(_, monitor_employees).
valid_identity_rule(_, design_processes).
valid_identity_rule(_, cross_control).
valid_identity_rule(_, define_billing_process).
valid_identity_rule(_, weekly_meetings).
valid_identity_rule(_, assign_roles).
valid_identity_rule(_, systematize).
valid_identity_rule(_, work_near_clients).
valid_identity_rule(_, use_CRM).
valid_identity_rule(_, communication_association).
*/

/*valid_identity_rule(organized, iva_90_days_delay).
valid_identity_rule(social, mercadopago).*/


regla_valida_combinacion(local, physical, physical_communications).
regla_valida_combinacion(local, physical, press_and_magazines).
regla_valida_combinacion(local, physical, influencers).
regla_valida_combinacion(local, physical, client_frequent_places).
regla_valida_combinacion(global, digital, digital_store).
regla_valida_combinacion(global, digital, talks_workshops).
regla_valida_combinacion(global, digital, digital_communications).
regla_valida_combinacion(global, digital, digital_marketing).
regla_valida_combinacion(global, digital, digital_payments).
regla_valida_combinacion(global, physical, logistic_association).
regla_valida_combinacion(global, physical, ecommerce_association).
regla_valida_combinacion(global, extrovert, international_contacts).
regla_valida_combinacion(global, allow_association, embassy_association).
regla_valida_combinacion(global, allow_association, international_association).
regla_valida_combinacion(extrovert, allow_association, brand_association).
regla_valida_combinacion(social, allow_association, brand_association).
regla_valida_combinacion(extrovert, allow_association, politic_mayor_association).
regla_valida_combinacion(social, allow_association, politic_mayor_association).
regla_valida_combinacion(non_social, allow_association, hire_business_manager).
regla_valida_combinacion(has_savings_or_funding, allow_association, hire_business_manager).
regla_valida_combinacion(has_savings_or_funding, strengthen_your_team, hire_experienced_employees).
regla_valida_combinacion(travel, doesnt_have_passport, arrange_passport).



final_suggest(create_sas).
final_suggest(iva_90_days_delay).
final_suggest(travel_documents).
final_suggest(accounting_balance).
final_suggest(handle_payments).
final_suggest(tax_checklist).
final_suggest(mercadopago).
final_suggest(public_accountant).
final_suggest(money_really_took).
final_suggest(salaries_check).
final_suggest(cross_check_control).
final_suggest(ensurance).
final_suggest(register_brand).
final_suggest(money_requirements).

final_suggest(sustitute_products).
final_suggest(pro_network).
final_suggest(study_competitors).
final_suggest(understand_customer).
final_suggest(understand_product).
final_suggest(aim_premium).



/* PARA PROBAR ONLINE
https://tio.run/##zX1pj@LckubnqV@B1LrS7dbbjY0xmJbuyAazGC8YvNNqpbwveN/tP99zICurMivZsu77zsynrIR44sSJiBPLWbLSPAkT99@Lxv@f/ykq17WL8u@EWVZ6@JKGevxiJnFpt@Ufg3Wih8UfgwX4PfeNqvSTGPxKWXZc@mX3Uua6X4IPVn4MoN85nWn@dfCf/z74XwPHj62XxAjs0q/t4j3B3eEuPz6w@@OVlflejsfsfhF7cQv9xt5/m9dDzp80QF2BvrGN/Na2np78I12zv3IDw@hpasfW3z/p7c6c/xjwuf2S6nnp/2K6H@xuEFyfLOB3l9c1Pp@mcs2T/uPbtz/Njc5eeWamh@HfB8KPL77bKYntq6PcHeQnFzDZK0P@EP@fZH4WfWACmrvr9YM0kR0Zdn7xij8uDM8S1nrov1dmXoX2K8k77JvQf9V6e2yHWyM/NfBHm9wW471t/qwBf99O73n@8WGAn3Z7L@Wr6T6grpjwz45pj013ZcQnB/xot6vDvzfZnzLQP2EvPdfN0s598Lmpf5fG0q0/fhnup/V@CPxquVv4K1b8q1PIWQvvk8gnHudc8CrEK5OXEIj9MVV8@vrmyB9ZPHCnX6d@febs58E/etPnOf/H4J0v/Rmj/L4rrfy8KF/5XtfRdzrBBmyse4QDy3ccOwdq/8j0PRKQ5bYb6i8Xr9SBaJEB0q55nvZ70MfRPnrlM8Oc9REnHygG//jHLzSA17e/DQ4SsxTAT3FH7gYiGGZAWJZtDQ5goRSDqvBjd6BXZRLpJfi0PMsBPvl7bNtWMTArszqr51/fGBzs2i/0fJBV9iDUiwGwx1lW0wf/tuxBmVjgH@cvLmooBoCdHQ/0MLLjBPwWD6o4OROG4Lez8YAIf7db007LBMDO39h5nuRn9y98MMVBEtZg@Q50FzDU8zNL3fO/vXcFoOPIzk3/uzv8AeyU22b5Eun5yT5PBij1Lj2o1y@B4kUvigR8/t0QdzE@cLk8vpCCz84eCAJO8QiVVGWRVLlpvxQ60P4j8qIEpd1LYYchmMWLk4Rh0tj5Q1iph6fipUnyU@El6WPyXLeAQF7SPKIEKwWoqPt9PX0BaOQ68OQvANIk9M9GjPQuyb8mohNWwIWf0KwHPOvFOK8ZuyjASLEOvP8R6GyIl9jW8xcz9MGyfjhKVdgviwP7iCyyL9792Iv0KH3C2YCvufZ51RQFqF6/r56HKFPPbacKwxfL1q3wrJeH4gB3frm46FOUT7vx2yq@FDLvKV/NBAJQ@Z3ykpmcKrY@x4ZPtIUOdOEAh6qAdmKze0R/8ZDCNnMb6PMh9dnSKfC718UBBrD0RxDLL0C0iUGAe0R5mea5yYzt/DKFokrTJH@Iu@RUI7f1Txb6ROrHoM8pQZZ/6UBY@7EyHsF0qwIfXeQBKyJ/SH@Kkyb@MRXLP2eElzz57NSfkD8D7qW8T8KH9u5AwgKp0O/th7MAC8WNn5Ojse1T2L3cWLKfjWwD44FI479G/jRPzCfUWnp2rqcPnc5KXopn/OBk2@nFrmAdOmfbPuR8XtU/zPSjD36EehdCQN2T22en7c7fPwTmCYjCTxrWsi/W@q7Kx1JFSeyXYNHYIHgmnf0YYLfgpx@/gDz6UiZgMiEoWMqHXgTEL6qw1MEHYDQz0U3vqRgDhgP9zTltWc/LmOSuHgPXfvOshy6egyzsAnI9Pr2EiR4XzyJSsDqecbJSP9kvpR@dF2gUVTFo1x7r7OJnr1UeWFS6AVb52bBGaEcPBcztUG/Pi8oCtXKuv7W@D2Ku65fnRPPqlw/pw8T8AnWVWmDOoEIojSQ5PXSz2s670jvPIInPCff5EKibZlLF5TNZrwQ1vQviSfwSgrx@Huynvz2cPSh1XnEgtHt@@nCwc3h5/RS0LrYe/ZrAf3rGeWvme5LSQdOvW9eqgl9JX61xKQfDs5YvFcUTuDerFyAM2E/Qp15X@OalG3j35VdG@jLwcaX/K8L@XjfZDyrkX3GvmT7Ji/O6Ob2A6sDqnoB9/OxrQ77P3V/Uy7tYAnJu6SXW@VDmKYFBMvoeUV4zxlO6uddA/Ep9rvlAkPfBQr6Eh5dLp3O9Tf0V61YgQYLQrd9tbj85Zn7uVs7tVKS7en@jSP@kiUuz8uLkNuj1XxereQF@u7rP3ejnuYCQnLggcV72ma704c9CPzv2s8h3JdbTg71vgJ8FXVfqs@iPLvMs6qZJ/hK1Ar90v2rEV8xvDPOc2b6zf9Jer9RfNtQr7GkLvZL/jml@Q1mgKrW7Tx3sY8CN8P0YeHNX4CoUWKa2w2cs9EZ5cx/tLupTyXSX@lrJdBdwpd67Su9dNgeqp0LIW3Vwtft9gPi5g/OA8MZO5pOoJwa416tdhbphYuhftvMb6llDvNE/belLTXi7NLyH@bUsfMz/kfTfOX5RnB@o18l/Gfa1lf0D9qxJQD9mVSBxnANvYee1b9pfnOBfxOGSD25OM7ELEL3PG05fNcefg7wrnX4@AHi/tq9vkz@Lvbdj/iyPJ9LkFdS9tuBZHk@v9Vfsz23np1PuZ@CHvesnMc/lqne4H3L9jqDvwJ@2z7@AfU7od9sEl/3fc/N@a0frKgMntFvf8IEbds@O@QFyzQf@NlhRKrsEqSoyfD0fXI4az8eVoADS44FlG3qQDPQfp/Dns1m7uKUc8N3dTvQ52Ntp37ODvO1o3qO/dRZ1D3PnSOAe7DnLeHrxxvvBlv1j@M2d5JvQn/tTb1tWj7ex7oXjS213jemV7a3f4nNtg/m3GF3bP/stRnf3lX9dVjoI/W/Xaq4PFyeX7XbnfHnh2S7yPebJ4Pce8qW8@x74dDIBcQ7QvHZ7XxzvI/RrVRvoGcLyB/bd5ucT1E8VrB8ht/fProKT0Hpatve0T0n2HnBbrrddqc@3@M7BodDr8@bCOR9975rvnV1@ldOnKT8PvXK8fI/Fjysg9@6G3GPwfuPx/lbkLS7vg8j3A4U755Vf4nLldOpL@KunVc9wMEEj64N/@2dH7P4JRm@nXlfPwb5du6lo@cXbtK3PtwcGT2A@3R94BvT@FsEz9LcLh6dEfH@j4BnA1Vsl12B2CyolELvvpZibiE@7EDcpb6Wi24DP@0EfaV/j/tNSv5E/EPmN7Dl5f1A/EvbsxPd39G/QPyfHT/JHgnhVlORJVTwtyU/Ac6Kca4KfprlxKvcI@Li7vY192Go8A/3YbtxG3Dp8f4y7e/7@CH7jCP4aDERC/VwLfNEaP2H3K7RbqAfF2S@wUP9@wFCUXWhfqQce0F8vgx6AHpVoj@BXzjmfAn46qPklpnjdhVp3cqCF58f5FffzLtMz1FevKj0D/OJyuw2/t@R@RT3swu/Dv7B8Pmn16wv33EMXxTkZdw@t8p703S2zh7RftcJ17F0TvId8Vf/vsV9R/gfN/ZOav7EF8xGhx63/mh3vK/8H3X17/iB7enn9QHxBTT@F@bqKfmCfUs/7ivR@iP5QKT8Ozu8r1y@FZVDwxIV7NnOSfzHFfYRevxjyGPd0oe1d1Ht5C1JcueX8GHLjGtr3ZyV2PKjt/vz8I03Aqrw88zB1MJBu2q@PTQp7oFugVQXiD/TLCxMGtGvgB1jI@mChW/qAB23GuUIeVPH5UZUFNGglg41teslgCA/08LzyLyewhT8ogF0GOgDb5uVVij64qPwixntpcqAjwNsOLy1y8m34b1cn@3LvAugNwO0dwE@kV26v3qD89VLsTYZ3O/ZP9J8vMN8g/OVW9A2qj9esb4155eHEDdKfTyZuqeVOTf5vw2/fbr7a@n6S@/MI/PY1vy/wuHon5Xn8x1O353E3b6ncZPHLSfznePg88nMH9vVRn9f5TRbvA@TX0e@OvR@CH97L@AKHW/c2H7J4tylx8w7GQybXjl@vvgX7HU73nojd5PduWk@eit9k9daW/rN87ot077D9d0T7LX7vu/ArPG8dKd7kd2tb@6/kff3Q@e7Z1c0xflz4enoPF@T/wcG@xM3BChQH4vf3snyVpwlIzH/ey7MECPfy83ntL@TfHz5/fwJ3riWAXp54OvGbL7b@v3sGB5R4tmDyZk5gWMt/fTZtg/IHaMJNcl8vfoNP5BeR/pPFV@4e/zTCX3CH8/Iw@iU@V5YGSAOvpStYQoO/nf8@jA6KisoGMfn/4UHYzdOsv/zM4wnMs@r7ckD65aTkece8OdIHs1/xs6ec9p@cx7PqAsUzCInfLp/xoFvX88HNxfZf9yf234DiunDnb96L99/X/5rRrvwh2OBWoPyrZVgGtlkBTz43kV5ZpsV/Dofgu//Iq3j4L//Syl5pzJLJmocx/KAc0lNswQsI2q9PsWhTluC7W49nhKw7db50YoVDW3hTc4igkSIVFEUqMDKdOhROxjEmxhtmAvMFtSsNRNhtvDG@aEdhSrgWEfQZQWgrz1UTZT/xrYRar3yBiudK2@KLhWbBiEubpNuoxO5gS@OD23EsD6lsMI1IkuLHGYFtZ@hSUSliddhs673GJiuUibyc3blHn8D5E2GbDEbzBkYNY7Z3MWK/j@0p27BDN0e53MMyPF6ahDuxFGq0QBazDc5Q0RJZjDsiECKaqz1hQZEVtKtiIk5auO7cAklde0b2fTPNdu3cMGmST9YTsgmGVkQs1bVHewQ6TWiM2LjHqWLp3nyD8lseFYaccUS9JjK3XR8L0bR3NXu0W2HrTlWpjJ5DHIV762y2ZZd8QsRwb64IbX8gsuVSrU4c1afovEcVixeSvU6GRNysN@vpVIQRoyND@qTYQw3KHMMimWN9UnmYNdldipxiW8P2x2lcdpY12gaxExjiOA26seb4E/k4E4h6OsshyGJ7Ipis8HQSeidvtBN4bRhws@OhPWgxSWKH1lGVbMjBKkEV7PrQ7HjOxP1uNxRzSNDtRa6L8CyzwmJW6to@sRtxI@VRn@yGi5Pc4d6QtnR5vzX9zSE4LlwPFs2es92VSsBau6e2XsbBcVP41b5Z@RjnqSNSF8jisJ@vZgfRJkaz8tiNGq/bZd4WG1J4MT7idC8tClUfZ8po4yTQIUiwaC7uOVLfHNHRehtguYkbjgqN0CDWfXkukQeT5/MpUVFrDUszDWN9Y2/SezJwgjgJzZZRyULPSmK@wMdDMsCbYUIYa9uAY5pSw33Gogama3OzouZ8BRmbgKDJPXO0g4OimsTQYsljJUL4dr4f8sLMYdpmhQRpgy/Uw64Y8hrSuMjMMg9u3UeOUGqLic/EwXwsEgexm1RLxZEX9l7Q1lywLwJ2PFawdWMsxlqq7gk32lXDo7fkKbXNCKshtjym4YsuR2R@viUom9i6Y1yYB/XJc44Rxe/HozUtITM/XtCV4HGCuOjd5CA1piScvG2w4lfmRvOUenZC6Kk3Wdh4XjRHfI8s/bU53/tU7E2yiq2pDF2PQ9PDRN9dBs3ysAlwGAO5Y0g663U9aXV7hYcJ75H51HICXtbk0m4ypNjw2LCU1l3EJXOyJ50txnARiw@FNU3uNvWWJ5ciOqPKGVKg62mMynQGwbiMI2hIcRY9Hs0T64RIqZKMmFnk2hk/4gxptDQKOOuqTOucfbjUp6pmwHLMaWtsJZsTvbMT/YCqysGPUOXU6VwdAPdfHLkqCqGTESXWApMry2PksjGzNR8x9JFu5KpgAllWc0UdyZOcU6ZbRoiO5CZVsJLyCUMpexIp0i1rhdvDyoZXyRo@TkdHNxQVH9Hr@KhvWw6CN6lWzWW2OFrbSgVWZoV@46zS2AwhkwaheAibtBUjGNcq5kReFGmjqIKlq3ins0isC0ptUwgjFyM7paeYpy0LVsTHEzmZd3U50sMg3yHqQdOg6WaqutuFC9GzXYEo/SmL5MNpBk9ydw1ntsx3sbQ2a6XaelImWPvjzGAhEiJRJE2p0Dw2krcM@02moJMihSt3V5RmuJNH4x49uInuw@iknVPH/BDZoqXx62iJi3EIZ23t5sutUOSd0ueZ6xYyLCuOmNpIESOGvGG4cGXTRdy1wlzMJjobGSoN54nYT9qggjv4NPW8YkybNSxV2zCLVTg5WjNHdjJc67Qxq6JI7FalG6Wp1aCCEcuSAsXE@tRUimDkAog3ub5ZljK87o0QtYK4IIsNyWQ5LOwQdLg92GpsVRWITWKFHPKyJrJ5SmJRi/JGpkYjhRMtQs8lPcG1RJVm3LE6Tusu1uu9niVwr5U0us8QtgqNUp7SI4Xxs2HQYPysaCzssi0HSguJJwlxSX779jmbwnKZB9MtXdYohof2Xtzo3XFG9yt7tmOTU4JEWIKcsChNCEGi/QUdkm2PYdLsNJrujRVSI1zH5@rCLo@gcELlo1gsFTgY7vqRNhyOkZkqWVI1Q/aOjGk0ZC0mC9hPl5tgNu5hTCSSYmYGKhSn1Xa6PRmFDldkR@5m2g46aJu82JvckuRzmtZFlB7afI3ww2YEsyk9aotEsSvNgU7VIqr4nUMjBs9MeknokaoYVifLh3ZD07CdVa2qJuow3GLnMpO2NKEAnlP1MJ2UOIqjrLghTIEUnHrml22ZO5V2IkpzR22nKEh89XRNUYnnMDiHnFamGncw7VNVxKcT01lM2IY@cVHDbAErEVlNZnjjemshP6UoxTLKqFt2GwcedmIvbeTdUdwj2FCm122tL3wxzjYuzjYNjBA8U5P7CBOQ8T6m547MT2RcNRxxuBSk8QnnkhhTUhOv9Hi@mToiamLxBFs6fFBKRaHC8Mijwn4M9WpZg/Zju9AkezdCBH6tMjVIUOpwoY4JkMb45ZGdyRidcfNcjEWcwmverjCqjsc1cVDrXmYEAWoiScRNKpgSUi3kTaPIJTu1SwWzZTjfHfJVDKbugDwPg@Da5dguzfC8PvFTn1acE0PPoF2qHZisdhZcWS7zeN8c1zikULp9jBro1O96VVzgh4BqCWTP5Ca8X6RpVhaMnntFhc9XMFONp/R2vV3Y3Rw7mJsZhuKOPvfrdIaPMeOghrPY6WTCNKuGSzyjoXaWR/q0xZjw2O4tj44Xi/S05tZT9pSkLS/qh77h7aY/EDo6liaFbw@pxoW7LMIniR3heGG4/caM2v2@ryXv2GxoVsZXE3jOzcITs1WAPw4D31gwNKtqe9NcdJTJFGt8i3lLbuEjELPZl0eZ4LIikbsRl/XbnU702YLw1nMXhCWVMJeFIe38KJvNMbPDDjqZ5QpMWMFcitAYFD8jY1QMQ82Fktbu0awvgTc2ik0IlmBFPUugx5G@QSQuQGhe3y5KU2LJ2qGGNlHqfE502lSPyJgPTvN1xRVjlp0JnjE2aGQ@ax2MWM09VzdnRLxojpphF8s10SlsZvidczhAJwuCw2I@P9KjtbaHsuOWOGgNNyY9DdWoJqCUXGbDTEZSxwWFUx0MA6hbo1NyxnUbpon57X6qk8myKNsAZSfO1GUWWRBFY28/z2PcrQVTL470@OhtIBqb9bC4L4enOpNHalwQB1STJq4woWR@Otpis2jDGaw86WapZ7kTcixMqcOmpjg/zXE@MXVds0YVjvsnso@UQnNttvFRtl65KTcReGXC4sFoVI8JUpOIBULvjrMto3drvAO8XWWBBLG4rAhI6u3Zchd6hMfvd9CREB0ZFMCozftMqtnkDKqXR0IeBssS3VYmPoaYyqNsT3fxtBIFcu@6QjMZAXKnSZJmaKA2e1xDuHscESXPHLYpOXe3ezYRyaNBkyp8ZHQQKJe4NOWx7WHKHEDnAyuLWXPUVyD27zV9Oc@izYI3RLLJ9/hqhiRwbR6zYbVfcpx/wsqwQToa4eiuKZjJrmbbrEVYtZsdN1zYbMbrzcKc0QrpH4h2ZDZpjlGUle96fOHQ8WnSjObGBpgA9TiYclYONBopIzdqXLZAUGLtaMhKE5kuIgXmwNBdnThKOl66p3LreruKC1BmX4dK2zGU6VtEmTMNBHoujz5s4bzI29Y5KWjMeUF2mG3VdN8EdXaUV1ttP51Hxayjxm21KGJb3q1JN8YOHsILrTBW9lgmaJrTjOVlP9z3XRprSb6ClgZGzySLEcxxuI3oiXqiLGUZLRzYxtWupuOEwlfroqQ7pN6oSTtf6K64NcfwlpmIh4RuU0FVpkdqdFJ01SUcWCtZyA2sjR8JTdnAFknKOXq0SLEWRvQiHsHuOKU1bMmI7MJSysweJ1NRVLUyERaOEawqAzoKrOgKQ9JM1FnTIwKDDkvKikqlwlTXPOlT3pBmhwNcFflJXLaQizV7aMPs5mOUckeiVmmeqc61c31K7rXeog2h94WJzadak3fOmgAOTnM2zEBSV8wONbo5qk63ZVIcQmciHG2OFoXW7TbDoYkjUhiPxRW9Zibcwjmm2gnCCTaUNJ13D32/mq6ReryeyglZ7ytYwgmHnkArjGzSjUcNCVvhxiHGbWBVoRx1TUAzTqMV4IOaVo7NDeQUoC6V5n3W@yK0UPQ5PIROsz3FHHKBBZ3VgcVMC2JG6LgdY@PY9ZYO6c/IRTf34nl0SIsFSLxmENXT/TazMBjZH0FPO3dOARoXDrXzvLYgxfmYrUdlMqPCzWo9thzbNfbDtEXmJWkudn1lDXerLsoa0UCQbdLThjP3CDbRQFUMBBannCpMMAPRRpjtzIwxQQ0pAo1P@K4@ssGpmgVEFBaqsTD56bRu@/niuHEq2AmgkjNqTlulpmcfnJlmZNpu0mx2rGANZ2hoimu5PUwhZC0JhWVTdSZOyMwyLNhuh4uJEqrkdFXUWW6quCJOENnIYHrY7fRy6Fv9sjsYC7ZCdOYICpCEb5b1pLLGe5aNUVRwcB40At2@AhVev@XVNbLZbptJdOImaMck2JSBOV@OaiUemjHkHIpGmSFzvEOTWVoRyrIeErtpPYxjm18fJhsSO9bIWtZ6FUFNwj5NYtKD@kWQWm1w3ObqfD7GQIwuKpU3@rI5FMV6jXa5KCcsRe8cVpNZkF3iMQMqKlpZOwilV9lwooDwjVm10zkbJMQIX4N1g9aBoVFitNS7ITYhItpnwqXmjIqtYCN9CR@0PQpKwE5c2IHqjXO@clq2mIQ4O13SLbarZL3G6WG16aFNqfpJkWfT2d7ZQIx8xFZG7edbjO83fMbLVAayPT@meUWt2zb2Mlsy9WWK6Sptk@jIOgWBjsdQxoTkchYoxxVfr1db3ko4S1uiiKOGWLo8HkRF7WdxS49GcNtHNtNKoynlb6Uomys5NmdKEoFCusGMeYQK1UgrDu0cHotld1CWR5PfrxAXp1NXNwLTSMt2DTtxq9CxHHqZAxtVls0xpYkJNp1G7cbtJ1KcH5D2WEpKy@xkM7HMHMXj/rDy8kCOzKFSH1tqhvekRTkTvxSzpTsl9GwmhZYgVJA0ScEiCwidkoNiM0zS2N5v2oWPruSDOjdGbm9VRyU/KkYoTwyjsnNbWmhCbSDmxj6tyxKSMN4R9q6zExFXmvSBO2XGVQjRTE5qsHyoJvQyatS2WMJpGc4djhpVlC0w1aoAfV2W7TibkBQkTLWJFMIseTxKCJkb@kJCqTIpYmd/6htIT9dCoxiGZYj7ob7S@TQM6lmV7Fftdih5OWEGewVRw@G4gjZTdCfk6bA1T6M9RmRUmCx3PQzwW6RVFpKQV2hNwiRTGt6Bm9LIqBqry9lMxSE2rparTjlkhY@5W65DhJHOcPI2COM1LiigvmsUVA41GStOyEGfoPjS0FcHc58phch2ezjU01wHqTXFNqDmpLfGusVgf5pp6@Fym0AI2oNoQhNT2Z8XvAQSWUisi6XI@10GR9CU2oQLlidTUgpn7omXpqrF0K6W6eP1Mdvt9NxYj2CZ44b@1vZSojaWe3wnt/BurE2T@WY@yicJxJMMMWIPEmiTT8EmGWUBv0UJUOqM5NMm0ogDCeO@JFUQ3etQhligAfJMF8XGfb6Hd8HUHh9XZpyMl5SSlVhaxscw8XRJ1BlroQ8P5sKUdcdXttJJ8kTMirmjWbZhpmAZNZWmy9w2GJMGDVNTHojUFCeBQueRVNGQKYXePgpJTzLsWbE8VvwElxqGzvBqlKE0KPhDI/Ez3l5E0w02lrKUEfCKp@KJlMW7U7o141jctWN9pMN9xu2VcbfiBLMGvRuucKpSTKHh6FDrSqkxx/2sBLUmzW6hzTzHMKRoE7Mz60gjK3@EjCuuw2ASSsoS2SsUtEY8BM2OlhDOKiZZlOl8svTDoy4pp13LZrG@5Lz9xM7Gvjx1prGxOo4UOA3ZAqpmXDGSBDj3MYNAQmGHh2OeHCUSEsYWo3GZvh6FxRFTQYyvICWQKFbeu3je@Z7BoWVmKcLoJK@aoTPBp7Zu7KQCFjxOzEegt1ZXuYKvmHxVndrlqK8EzCSUVmJASU35YRZNIEjBxpi9WfTlQpGlcgKtLZdU5zI/zo7ixEUKx5dCblr7BaPWwno7O/k4Uqu0gqblKtzOYEQ8OJGsdLZezCAmQ8W5nFd4L0U2x@ajPoe2UkeMFD0TKslqeEfd68ZJljatKYNKykqKdaesgx1MEDTViP4wombcrh86c2XRIFOmyYFIdTQKrXHGlXKaolG5NnDNkhkzHRlIlcWVhhsCEpuQcmSmVE@kJ3YxG9k5PVuG9a7eCbAorY92Z7YCCu/UKTsZN8ZpPQ22OZhkqKAcGmnKlFvSFjUhOW7WhTEKw5mZ5zZbR1tnimURrIseVVrbLERVf0XPRtxxX5Ia2pfiIpdss1ExV1dW@wXEYj7FDpFii5S94q53Jex3cgAqupnQHeSomudFve@aMhI0VetUECNaWe6T@JjZ01TfcGQxnMrtlCtBW71nDtG0YY4wDWYFw/zQnLalIJfWOst5UdTCnD22o9jQo7yZCYkysZUdhqkZy09x4IJZoJhHlY6Hq2DT7MTeU3ZwLWyDNTSBUkuAJqi0LeIAqThrWwucuCxavuVkGJTOMXD5pStHdFFkBXwoNdLyQ5oMaFgLDWIDG4p6QF3fjpt4k2PNeki3ybpXVZkXh/AO1ZlV0Nq6rXLGjlPCYtnB8PBUQAHCW/Bosxvtw1aCImwqCuugImvUlJOAnbjQPDcSZIwWcWumuQIdViNvO2WqTaiJujNJeo@IIrwf5WLL4jvfMFWEToKwagM1ZEzvODqSna4TrCuN2URgJkbYmCloHMw5URcHk1wNlTi3hmzAzWKYwRRjZUSGzc4QaRYuhK4W3NDyCMxZDa1wOTT4zNv66HC4PaK1uOE1nBsSxLdvFMdL4uAf/3tw729qfe3w6cqJk/Dzz22/XC4znk@cVH65EJfkefBP3w/@MfivXy5eXf9rQB8uld25L/ffl/tyP/9vm/9b0/w/

suggest(legal_plan, [wants_order,wants_recognition,product,indumentaria,otro,allow_sell_workshops,digital,global,dont_allow_association], [has_savings_or_funding,doesnt_have_account,doesnt_have_credit_history,doesnt_have_passport,university,alone,doesnt_have_balance,doesnt_have_followers,has_achievements,has_contacts], [non_social,extrovert,stressfully,independent,young_client], Sugerencias_final).
suggest(legal_plan, [wants_recognition, travel], [has_savings_or_funding, has_achievements], [organized, social], Sugerencias_final).
*/
